/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a AdcConfigMessage
 */
public class AdcConfigMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int ADC_CONFIG_MESSAGE_MAX_ORDINAL = 3;

	private static final int ADC_CONFIG_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int ADC_CONFIG_MESSAGE_CONFIG_CHANNEL_INDEX = 0;
	private static final int ADC_CONFIG_MESSAGE_CONFIG_ENABLED_INDEX = 1;
	private static final int ADC_CONFIG_MESSAGE_CONFIG_GAIN_INDEX = 8;
	private static final int ADC_CONFIG_MESSAGE_CONFIG_OFFSET_INDEX = 12;
	private static final int ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX = 8;
	private static final int ADC_CONFIG_MESSAGE_CONFIG_TIME_CONSTANT_SECONDS_INDEX = 4;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema

	//Bit Nums
	private static final int ADC_CONFIG_MESSAGE_CONFIG_ENABLED_BIT_NUM = 0;

	//Sequence Element Byte Counts
	private static final int ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 16;
	/**
	 * A constructor to create a AdcConfigMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	private AdcConfigMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a AdcConfigMessage for transmission.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static AdcConfigMessage make(BlueberryBuffer buf) {
		AdcConfigMessage msg = new AdcConfigMessage(buf);
		msg.setupHeader(ADC_CONFIG_MESSAGE_KEY, ADC_CONFIG_MESSAGE_MAX_ORDINAL, ADC_CONFIG_MESSAGE_LENGTH);
		msg.m_buf.writeUint16(ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty AdcConfigMessage for transmission.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static AdcConfigMessage makeEmpty(BlueberryBuffer buf) {
		AdcConfigMessage msg = new AdcConfigMessage(buf);
		msg.setupHeader(ADC_CONFIG_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a AdcConfigMessage.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static AdcConfigMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, ADC_CONFIG_MESSAGE_KEY)){
			return null;
		}
		AdcConfigMessage msg = new AdcConfigMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey config parameters for ADCs
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= ADC_CONFIG_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the channel field
	 * @param i0 - index of config sequence.
	 */
	public int getConfigChannel(int i0){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the channel field
	 * @param i0 - index of config sequence.
	 * @param channel
	 */
	public void setConfigChannel(int i0, int channel){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , channel);
	}
	/**
	 * A getter for the enabled field
	 * @param i0 - index of config sequence.
	 */
	public boolean isConfigEnabled(int i0){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_ENABLED_INDEX;
		return m_buf.readBit(i , ADC_CONFIG_MESSAGE_CONFIG_ENABLED_BIT_NUM);
	}
	/**
	 * A setter for the enabled field
	 * @param i0 - index of config sequence.
	 * @param enabled
	 */
	public void setConfigEnabled(int i0, boolean enabled){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_ENABLED_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeBit(i , ADC_CONFIG_MESSAGE_CONFIG_ENABLED_BIT_NUM, enabled);
	}
	/**
	 * A getter for the timeConstantSeconds field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigTimeConstantSeconds(int i0){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_TIME_CONSTANT_SECONDS_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the timeConstantSeconds field
	 * @param i0 - index of config sequence.
	 * @param timeConstantSeconds
	 */
	public void setConfigTimeConstantSeconds(int i0, double timeConstantSeconds){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_TIME_CONSTANT_SECONDS_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , timeConstantSeconds);
	}
	/**
	 * A getter for the gain field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigGain(int i0){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_GAIN_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the gain field
	 * @param i0 - index of config sequence.
	 * @param gain
	 */
	public void setConfigGain(int i0, double gain){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_GAIN_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , gain);
	}
	/**
	 * A getter for the offset field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigOffset(int i0){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_OFFSET_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the offset field
	 * @param i0 - index of config sequence.
	 * @param offset
	 */
	public void setConfigOffset(int i0, double offset){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_CONFIG_MESSAGE_CONFIG_OFFSET_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , offset);
	}
	/**
	 * A function to initialize a Adc Config Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initConfig(int n){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Adc Config Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getConfigSequenceLength(){
		int i = 0;
		i = i + ADC_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
