/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a AdcDataMessage
 */
public class AdcDataMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int ADC_DATA_MESSAGE_MAX_ORDINAL = 3;

	private static final int ADC_DATA_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int ADC_DATA_MESSAGE_DATA_DATA_INDEX = 0;
	private static final int ADC_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int ADC_DATA_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 4;
	/**
	 * A constructor to create a AdcDataMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey data from all configured ADCs
	 * @param buf - the message buffer to add the message to
	 */
	private AdcDataMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a AdcDataMessage for transmission.
	 * A message to convey data from all configured ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static AdcDataMessage make(BlueberryBuffer buf) {
		AdcDataMessage msg = new AdcDataMessage(buf);
		msg.setupHeader(ADC_DATA_MESSAGE_KEY, ADC_DATA_MESSAGE_MAX_ORDINAL, ADC_DATA_MESSAGE_LENGTH);
		msg.m_buf.writeUint16(ADC_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty AdcDataMessage for transmission.
	 * A message to convey data from all configured ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static AdcDataMessage makeEmpty(BlueberryBuffer buf) {
		AdcDataMessage msg = new AdcDataMessage(buf);
		msg.setupHeader(ADC_DATA_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a AdcDataMessage.
	 * A message to convey data from all configured ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static AdcDataMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, ADC_DATA_MESSAGE_KEY)){
			return null;
		}
		AdcDataMessage msg = new AdcDataMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey data from all configured ADCs
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= ADC_DATA_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the data field
	 * @param i0 - index of data sequence.
	 */
	public double getDataData(int i0){
		int i = 0;
		i = i + ADC_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_DATA_MESSAGE_DATA_DATA_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the data field
	 * @param i0 - index of data sequence.
	 * @param data
	 */
	public void setDataData(int i0, double data){
		int i = 0;
		i = i + ADC_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + ADC_DATA_MESSAGE_DATA_DATA_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , data);
	}
	/**
	 * A function to initialize a Adc Data Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initData(int n){
		int i = 0;
		i = i + ADC_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = ADC_DATA_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Adc Data Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getDataSequenceLength(){
		int i = 0;
		i = i + ADC_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
