/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.EnumLookup;

public interface BlueberryDevicesConstants {
	/**
	 * A message to convey config parameters for ADCs
	 */
	public static final int ADC_CONFIG_MESSAGE_KEY = 0x4244f7f2;
	/**
	 * A message to convey data from all configured ADCs
	 */
	public static final int ADC_DATA_MESSAGE_KEY = 0x4244fc9d;
	/**
	 * A message to convey a sequence of app data - an array of floats for various purposes
	 */
	public static final int APP_DATA_MESSAGE_KEY = 0x4244dd4b;
	/**
	 * a general purpose message that can convey any number of various sequences to convey trajectories, update responses, or configuration
	 */
	public static final int FEEDBACK_MESSAGE_KEY = 0x42444d78;
	/**
	 * a message to convey flash programming data
	 */
	public static final int FLASH_PROGRAM_MESSAGE_KEY = 0x4244d12c;
	/**
	 * A message to convey config parameters for ADCs
	 */
	public static final int GPIO_CONFIG_MESSAGE_KEY = 0x4244d14e;
	/**
	 * A message to convey the digital values of each GPIO pin
	 * Each element in the sequence is the pin values of a port: Port A, Port B ... Port N
	 */
	public static final int GPIO_PINS_MESSAGE_KEY = 0x424471ef;
	/**
	 *  A message to define an I2C transaction to be sent out
	 */
	public static final int I_2_C_TRANSACTION_MESSAGE_KEY = 0x424426ed;
	/**
	 * A message to convey the unique ID of this devices
	 */
	public static final int ID_MESSAGE_KEY = 0x42448ca5;
	/**
	 * A message to convey one or more coordinates
	 */
	public static final int IMU_DATA_MESSAGE_KEY = 0x424465a1;
	/**
	 * A message to convey setup parameters for the oscope module
	 */
	public static final int OSCOPE_CONFIG_MESSAGE_KEY = 0x42447e1d;
	/**
	 * a message to convey a single channel of oscope data
	 * this can also be used to configure a channel - data would be zero length in that case
	 */
	public static final int OSCOPE_DATA_MESSAGE_KEY = 0x4244831d;
	/**
	 *  A message to define an SPI transaction to be sent out
	 */
	public static final int SPI_TRANSACTION_MESSAGE_KEY = 0x424425ed;
	/**
	 * A message to convey config parameters for Thermistors
	 */
	public static final int THERMISTOR_CONFIG_MESSAGE_KEY = 0x4244aae3;
	/**
	 * A message to convey data from all configured ADCs
	 */
	public static final int THERMISTOR_DATA_MESSAGE_KEY = 0x4244d51a;
	/**
	 * A message for time synchronization.
	 * This message will likely be deprecated soon. 
	 */
	public static final int TIME_MESSAGE_KEY = 0x42443c5b;
	/**
	 * An improved message for time synchronization that uses the new Time64 deined type
	 */
	public static final int TIME_SYNC_MESSAGE_KEY = 0x4244767d;
	/**
	 * A message to convey hardware and firmware versions in addition to hardware type
	 */
	public static final int VERSION_MESSAGE_KEY = 0x42448366;
	/**
	 * a request by the bus controller to all devices that have not communicated successfully recently
	 * the controller can specify the probability and timeframe that the peripherals will respond
	 * the peripherals will respond with an idPayload
	 */
	public static final int WHOS_THERE_MESSAGE_KEY = 0x42441971;

	//*************************************************************************************
	//Topic String Constants
	//*************************************************************************************

	public static final String ADC_CONFIG_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/adc-config";
	public static final String ADC_DATA_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/adc-data";
	public static final String APP_DATA_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/app-data";
	public static final String FEEDBACK_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/feedback";
	public static final String FLASH_PROGRAM_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/flash_program";
	public static final String GPIO_CONFIG_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/gpio-pin-config";
	public static final String GPIO_PINS_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/gpio-pins";
	public static final String I_2_C_TRANSACTION_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/i2c-transaction";
	public static final String ID_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/id";
	public static final String IMU_DATA_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/imu-data";
	public static final String OSCOPE_CONFIG_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/oscope-config";
	public static final String OSCOPE_DATA_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/oscope-data";
	public static final String SPI_TRANSACTION_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/spi-transaction";
	public static final String THERMISTOR_CONFIG_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/thermistor-config";
	public static final String THERMISTOR_DATA_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/thermistor-data";
	public static final String TIME_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/time";
	public static final String TIME_SYNC_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/timesync";
	public static final String VERSION_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/version";
	public static final String WHOS_THERE_MESSAGE_TOPIC = "blueberry/devices/{device_type}/{nid}/whos-there";


	/**
	 * an enum to specify a port pin
	 * this is constructed with the top nibble representing the port and the bottom nibble the pin number
	 */
	public enum PortPinEnum {
		GPIO_A0_PIN((byte)0x0000),
		GPIO_A1_PIN((byte)0x0001),
		GPIO_A2_PIN((byte)0x0002),
		GPIO_A3_PIN((byte)0x0003),
		GPIO_A4_PIN((byte)0x0004),
		GPIO_A5_PIN((byte)0x0005),
		GPIO_A6_PIN((byte)0x0006),
		GPIO_A7_PIN((byte)0x0007),
		GPIO_A8_PIN((byte)0x0008),
		GPIO_A9_PIN((byte)0x0009),
		GPIO_A10_PIN((byte)0x000a),
		GPIO_A11_PIN((byte)0x000b),
		GPIO_A12_PIN((byte)0x000c),
		GPIO_A13_PIN((byte)0x000d),
		GPIO_A14_PIN((byte)0x000e),
		GPIO_A15_PIN((byte)0x000f),
		GPIO_B0_PIN((byte)0x0010),
		GPIO_B1_PIN((byte)0x0011),
		GPIO_B2_PIN((byte)0x0012),
		GPIO_B3_PIN((byte)0x0013),
		GPIO_B4_PIN((byte)0x0014),
		GPIO_B5_PIN((byte)0x0015),
		GPIO_B6_PIN((byte)0x0016),
		GPIO_B7_PIN((byte)0x0017),
		GPIO_B8_PIN((byte)0x0018),
		GPIO_B9_PIN((byte)0x0019),
		GPIO_B10_PIN((byte)0x001a),
		GPIO_B11_PIN((byte)0x001b),
		GPIO_B12_PIN((byte)0x001c),
		GPIO_B13_PIN((byte)0x001d),
		GPIO_B14_PIN((byte)0x001e),
		GPIO_B15_PIN((byte)0x001f),
		GPIO_C0_PIN((byte)0x0020),
		GPIO_C1_PIN((byte)0x0021),
		GPIO_C2_PIN((byte)0x0022),
		GPIO_C3_PIN((byte)0x0023),
		GPIO_C4_PIN((byte)0x0024),
		GPIO_C5_PIN((byte)0x0025),
		GPIO_C6_PIN((byte)0x0026),
		GPIO_C7_PIN((byte)0x0027),
		GPIO_C8_PIN((byte)0x0028),
		GPIO_C9_PIN((byte)0x0029),
		GPIO_C10_PIN((byte)0x002a),
		GPIO_C11_PIN((byte)0x002b),
		GPIO_C12_PIN((byte)0x002c),
		GPIO_C13_PIN((byte)0x002d),
		GPIO_C14_PIN((byte)0x002e),
		GPIO_C15_PIN((byte)0x002f),
		GPIO_D0_PIN((byte)0x0030),
		GPIO_D1_PIN((byte)0x0031),
		GPIO_D2_PIN((byte)0x0032),
		GPIO_D3_PIN((byte)0x0033),
		GPIO_D4_PIN((byte)0x0034),
		GPIO_D5_PIN((byte)0x0035),
		GPIO_D6_PIN((byte)0x0036),
		GPIO_D7_PIN((byte)0x0037),
		GPIO_D8_PIN((byte)0x0038),
		GPIO_D9_PIN((byte)0x0039),
		GPIO_D10_PIN((byte)0x003a),
		GPIO_D11_PIN((byte)0x003b),
		GPIO_D12_PIN((byte)0x003c),
		GPIO_D13_PIN((byte)0x003d),
		GPIO_D14_PIN((byte)0x003e),
		GPIO_D15_PIN((byte)0x003f),
		GPIO_E0_PIN((byte)0x0040),
		GPIO_E1_PIN((byte)0x0041),
		GPIO_E2_PIN((byte)0x0042),
		GPIO_E3_PIN((byte)0x0043),
		GPIO_E4_PIN((byte)0x0044),
		GPIO_E5_PIN((byte)0x0045),
		GPIO_E6_PIN((byte)0x0046),
		GPIO_E7_PIN((byte)0x0047),
		GPIO_E8_PIN((byte)0x0048),
		GPIO_E9_PIN((byte)0x0049),
		GPIO_E10_PIN((byte)0x004a),
		GPIO_E11_PIN((byte)0x004b),
		GPIO_E12_PIN((byte)0x004c),
		GPIO_E13_PIN((byte)0x004d),
		GPIO_E14_PIN((byte)0x004e),
		GPIO_E15_PIN((byte)0x004f),
		GPIO_F0_PIN((byte)0x0050),
		GPIO_F1_PIN((byte)0x0051),
		GPIO_F2_PIN((byte)0x0052),
		GPIO_F3_PIN((byte)0x0053),
		GPIO_F4_PIN((byte)0x0054),
		GPIO_F5_PIN((byte)0x0055),
		GPIO_F6_PIN((byte)0x0056),
		GPIO_F7_PIN((byte)0x0057),
		GPIO_F8_PIN((byte)0x0058),
		GPIO_F9_PIN((byte)0x0059),
		GPIO_F10_PIN((byte)0x005a),
		GPIO_F11_PIN((byte)0x005b),
		GPIO_F12_PIN((byte)0x005c),
		GPIO_F13_PIN((byte)0x005d),
		GPIO_F14_PIN((byte)0x005e),
		GPIO_F15_PIN((byte)0x005f),
		GPIO_G0_PIN((byte)0x0060),
		GPIO_G1_PIN((byte)0x0061),
		GPIO_G2_PIN((byte)0x0062),
		GPIO_G3_PIN((byte)0x0063),
		GPIO_G4_PIN((byte)0x0064),
		GPIO_G5_PIN((byte)0x0065),
		GPIO_G6_PIN((byte)0x0066),
		GPIO_G7_PIN((byte)0x0067),
		GPIO_G8_PIN((byte)0x0068),
		GPIO_G9_PIN((byte)0x0069),
		GPIO_G10_PIN((byte)0x006a),
		GPIO_G11_PIN((byte)0x006b),
		GPIO_G12_PIN((byte)0x006c),
		GPIO_G13_PIN((byte)0x006d),
		GPIO_G14_PIN((byte)0x006e),
		GPIO_G15_PIN((byte)0x006f),
		GPIO_H0_PIN((byte)0x0070),
		GPIO_H1_PIN((byte)0x0071),
		GPIO_H2_PIN((byte)0x0072),
		GPIO_H3_PIN((byte)0x0073),
		GPIO_H4_PIN((byte)0x0074),
		GPIO_H5_PIN((byte)0x0075),
		GPIO_H6_PIN((byte)0x0076),
		GPIO_H7_PIN((byte)0x0077),
		GPIO_H8_PIN((byte)0x0078),
		GPIO_H9_PIN((byte)0x0079),
		GPIO_H10_PIN((byte)0x007a),
		GPIO_H11_PIN((byte)0x007b),
		GPIO_H12_PIN((byte)0x007c),
		GPIO_H13_PIN((byte)0x007d),
		GPIO_H14_PIN((byte)0x007e),
		GPIO_H15_PIN((byte)0x007f),
		GPIO_I0_PIN((byte)0x0080),
		GPIO_I1_PIN((byte)0x0081),
		GPIO_I2_PIN((byte)0x0082),
		GPIO_I3_PIN((byte)0x0083),
		GPIO_I4_PIN((byte)0x0084),
		GPIO_I5_PIN((byte)0x0085),
		GPIO_I6_PIN((byte)0x0086),
		GPIO_I7_PIN((byte)0x0087),
		GPIO_I8_PIN((byte)0x0088),
		GPIO_I9_PIN((byte)0x0089),
		GPIO_I10_PIN((byte)0x008a),
		GPIO_I11_PIN((byte)0x008b),
		GPIO_I12_PIN((byte)0x008c),
		GPIO_I13_PIN((byte)0x008d),
		GPIO_I14_PIN((byte)0x008e),
		GPIO_I15_PIN((byte)0x008f),
		GPIO_NULL_PIN((byte)0x00ff),
		;
		private static EnumLookup<PortPinEnum> m_lookup = new EnumLookup<PortPinEnum>();
		private int value;
		private PortPinEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static PortPinEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(PortPinEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	/**
	 * A selection of units for the setpoint.
	 * Mostly just to select between angular units and units that do not loop
	 * For now this is not inteded to stray beyond SI
	 */
	public enum UnitEnum {
		METRES((byte)0x0000),
		RADIANS((byte)0x0001),
		METRES_PER_SECOND((byte)0x0003),
		RADIANS_PER_SECOND((byte)0x0004),
		DEGREES((byte)0x0005),
		METRES_PER_SECOND_SQUARED((byte)0x0006),
		RADIANS_PER_SECOND_SQUARED((byte)0x0007),
		NEWTONS((byte)0x0008),
		NEWTON_METRES((byte)0x0009),
		;
		private static EnumLookup<UnitEnum> m_lookup = new EnumLookup<UnitEnum>();
		private int value;
		private UnitEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static UnitEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(UnitEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	/**
	 * Defines where the feedback controller should get its input from
	 */
	public enum PlumbingTypeEnum {
		UNCONFIGURED((byte)0x0000),
		OPEN_LOOP((byte)0x0001),
		TX_APP_DATA((byte)0x0002),
		RX_APP_DATA((byte)0x0003),
		STREAM((byte)0x0004),
		;
		private static EnumLookup<PlumbingTypeEnum> m_lookup = new EnumLookup<PlumbingTypeEnum>();
		private int value;
		private PlumbingTypeEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static PlumbingTypeEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(PlumbingTypeEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum FlashProgramStateEnum {
		DO_NOTHING_REQUEST((byte)0x0000),
		UPLOAD_REQUEST((byte)0x0001),
		RUN_REQUEST((byte)0x0002),
		OVERWRITE_REQUEST((byte)0x0003),
		CLEAR_REQUEST((byte)0x0004),
		STOP_REQUEST((byte)0x0005),
		IMAGE_GOOD_RESPONSE((byte)0x0006),
		IMAGE_BAD_RESPONSE((byte)0x0007),
		IMAGE_CLEAR_RESPONSE((byte)0x0008),
		UPLOADING_RESPONSE((byte)0x0009),
		UPLOAD_BAD_RESPONSE((byte)0x000a),
		WILL_RUN_RESPONSE((byte)0x000b),
		RUNNING_RESPONSE((byte)0x000c),
		OVERWRITING_RESPONSE((byte)0x000d),
		CLEARING_RESPONSE((byte)0x000e),
		;
		private static EnumLookup<FlashProgramStateEnum> m_lookup = new EnumLookup<FlashProgramStateEnum>();
		private int value;
		private FlashProgramStateEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static FlashProgramStateEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(FlashProgramStateEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum GpioDirEnum {
		INPUT((byte)0x0000),
		OUTPUT((byte)0x0001),
		ANALOG((byte)0x0002),
		OUTPUT_LOW((byte)0x0003),
		OUTPUT_HIGH((byte)0x0004),
		AF0((byte)0x0005),
		AF1((byte)0x0006),
		AF2((byte)0x0007),
		AF3((byte)0x0008),
		AF4((byte)0x0009),
		AF5((byte)0x000a),
		AF6((byte)0x000b),
		AF7((byte)0x000c),
		AF8((byte)0x000d),
		AF9((byte)0x000e),
		AF10((byte)0x000f),
		AF11((byte)0x0010),
		AF12((byte)0x0011),
		AF13((byte)0x0012),
		AF14((byte)0x0013),
		AF15((byte)0x0014),
		;
		private static EnumLookup<GpioDirEnum> m_lookup = new EnumLookup<GpioDirEnum>();
		private int value;
		private GpioDirEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static GpioDirEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(GpioDirEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum I2CDevBbEnum {
		I2CNULL_DEV((byte)0x00ff),
		I2C1_DEV((byte)0x0000),
		I2C2_DEV((byte)0x0001),
		I2C3_DEV((byte)0x0002),
		I2C4_DEV((byte)0x0003),
		;
		private static EnumLookup<I2CDevBbEnum> m_lookup = new EnumLookup<I2CDevBbEnum>();
		private int value;
		private I2CDevBbEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static I2CDevBbEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(I2CDevBbEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum TriggerPosEnum {
		FIRST_QUARTER_TRIG_POS((byte)0x0000),
		SECOND_QUARTER_TRIG_POS((byte)0x0001),
		THIRD_QUARTER_TRIG_POS((byte)0x0002),
		FOURTH_QUARTER_TRIG_POS((byte)0x0003),
		;
		private static EnumLookup<TriggerPosEnum> m_lookup = new EnumLookup<TriggerPosEnum>();
		private int value;
		private TriggerPosEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static TriggerPosEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(TriggerPosEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum ClockSpecBbEnum {
		SPI_CPOL_0_CPHA_0((byte)0x0000),
		SPI_CPOL_0_CPHA_1((byte)0x0001),
		SPI_CPOL_1_CPHA_0((byte)0x0002),
		SPI_CPOL_1_CPHA_1((byte)0x0003),
		;
		private static EnumLookup<ClockSpecBbEnum> m_lookup = new EnumLookup<ClockSpecBbEnum>();
		private int value;
		private ClockSpecBbEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static ClockSpecBbEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(ClockSpecBbEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum SpiDevBbEnum {
		SPINULL_DEV((byte)0x00ff),
		SPI1_DEV((byte)0x0000),
		SPI2_DEV((byte)0x0001),
		SPI3_DEV((byte)0x0002),
		SPI4_DEV((byte)0x0003),
		SPI5_DEV((byte)0x0004),
		;
		private static EnumLookup<SpiDevBbEnum> m_lookup = new EnumLookup<SpiDevBbEnum>();
		private int value;
		private SpiDevBbEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static SpiDevBbEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(SpiDevBbEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum BaudDivBbEnum {
		SPI_DIV_2((byte)0x0000),
		SPI_DIV_4((byte)0x0001),
		SPI_DIV_8((byte)0x0002),
		SPI_DIV_16((byte)0x0003),
		SPI_DIV_32((byte)0x0004),
		SPI_DIV_64((byte)0x0005),
		SPI_DIV_128((byte)0x0006),
		SPI_DIV_256((byte)0x0007),
		;
		private static EnumLookup<BaudDivBbEnum> m_lookup = new EnumLookup<BaudDivBbEnum>();
		private int value;
		private BaudDivBbEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static BaudDivBbEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(BaudDivBbEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	/**
	 * an enum to convey PCB type
	 */
	public enum HwTypeEnum {
		UNDEFINED((short)0xffff),
		LEGACY((short)0x0000),
		BLUE_SERVO((short)0x0001),
		LUMEN((short)0x0002),
		NUCLEO((short)0x0003),
		BLUE_ESC((short)0x0004),
		GIGABOARD((short)0x0005),
		BLUE_BRIDGE((short)0x0006),
		;
		private static EnumLookup<HwTypeEnum> m_lookup = new EnumLookup<HwTypeEnum>();
		private int value;
		private HwTypeEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static HwTypeEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(HwTypeEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
	public enum McuTypeEnum {
		UNDEFINED((byte)0x00ff),
		STM32F446((byte)0x0001),
		STM32H563((byte)0x0002),
		STM32H573((byte)0x0003),
		STM32G071((byte)0x0004),
		;
		private static EnumLookup<McuTypeEnum> m_lookup = new EnumLookup<McuTypeEnum>();
		private int value;
		private McuTypeEnum(int v){
			value = v;
		}
		public int getValue(){
			return value;
		}
		public static McuTypeEnum lookup(int i){
			if(m_lookup.size() == 0) {
				for(McuTypeEnum e : values()) {
					m_lookup.add(e.getValue(), e);
				}
			}
			return m_lookup.lookup(i);
		}
	}
}
