/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a FeedbackMessage
 */
public class FeedbackMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int FEEDBACK_MESSAGE_MAX_ORDINAL = 5;

	private static final int FEEDBACK_MESSAGE_LENGTH = 20;

	//These values are used to index into this message to access the various fields.
	private static final int FEEDBACK_MESSAGE_CONFIG_CHANNEL_INDEX = 0;
	private static final int FEEDBACK_MESSAGE_CONFIG_C_0_INDEX = 24;
	private static final int FEEDBACK_MESSAGE_CONFIG_C_1_INDEX = 28;
	private static final int FEEDBACK_MESSAGE_CONFIG_C_2_INDEX = 32;
	private static final int FEEDBACK_MESSAGE_CONFIG_D_1_INDEX = 36;
	private static final int FEEDBACK_MESSAGE_CONFIG_D_2_INDEX = 40;
	private static final int FEEDBACK_MESSAGE_CONFIG_ENABLE_INDEX = 2;
	private static final int FEEDBACK_MESSAGE_CONFIG_INPUT_CHANNEL_INDEX = 21;
	private static final int FEEDBACK_MESSAGE_CONFIG_INPUT_TYPE_INDEX = 3;
	private static final int FEEDBACK_MESSAGE_CONFIG_MAX_INPUT_INDEX = 8;
	private static final int FEEDBACK_MESSAGE_CONFIG_MAX_OUTPUT_INDEX = 16;
	private static final int FEEDBACK_MESSAGE_CONFIG_MIN_INPUT_INDEX = 4;
	private static final int FEEDBACK_MESSAGE_CONFIG_MIN_OUTPUT_INDEX = 12;
	private static final int FEEDBACK_MESSAGE_CONFIG_OUTPUT_CHANNEL_INDEX = 22;
	private static final int FEEDBACK_MESSAGE_CONFIG_OUTPUT_TYPE_INDEX = 20;
	private static final int FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX = 8;
	private static final int FEEDBACK_MESSAGE_CONFIG_UNIT_INDEX = 1;
	private static final int FEEDBACK_MESSAGE_RESPONSE_ACTUAL_INDEX = 4;
	private static final int FEEDBACK_MESSAGE_RESPONSE_CHANNEL_INDEX = 0;
	private static final int FEEDBACK_MESSAGE_RESPONSE_END_TIME_INDEX = 16;
	private static final int FEEDBACK_MESSAGE_RESPONSE_OUTPUT_INDEX = 12;
	private static final int FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX = 16;
	private static final int FEEDBACK_MESSAGE_RESPONSE_QUEUE_LENGTH_INDEX = 1;
	private static final int FEEDBACK_MESSAGE_RESPONSE_SETPOINT_INDEX = 8;
	private static final int FEEDBACK_MESSAGE_TRAJECTORIES_CHANNEL_INDEX = 0;
	private static final int FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX = 12;
	private static final int FEEDBACK_MESSAGE_TRAJECTORIES_SETPOINT_INDEX = 4;
	private static final int FEEDBACK_MESSAGE_TRAJECTORIES_SETPOINT_RATE_INDEX = 8;
	private static final int FEEDBACK_MESSAGE_TRAJECTORIES_TIME_INDEX = 12;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema

	//Bit Nums
	private static final int FEEDBACK_MESSAGE_CONFIG_ENABLE_BIT_NUM = 0;

	//Sequence Element Byte Counts
	private static final int FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 44;
	private static final int FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 20;
	private static final int FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 16;
	/**
	 * A constructor to create a FeedbackMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * a general purpose message that can convey any number of various sequences to convey trajectories, update responses, or configuration
	 * @param buf - the message buffer to add the message to
	 */
	private FeedbackMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a FeedbackMessage for transmission.
	 * a general purpose message that can convey any number of various sequences to convey trajectories, update responses, or configuration
	 * @param buf - the message buffer to add the message to
	 */
	public static FeedbackMessage make(BlueberryBuffer buf) {
		FeedbackMessage msg = new FeedbackMessage(buf);
		msg.setupHeader(FEEDBACK_MESSAGE_KEY, FEEDBACK_MESSAGE_MAX_ORDINAL, FEEDBACK_MESSAGE_LENGTH);
		msg.m_buf.writeUint16(FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		msg.m_buf.writeUint16(FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		msg.m_buf.writeUint16(FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty FeedbackMessage for transmission.
	 * a general purpose message that can convey any number of various sequences to convey trajectories, update responses, or configuration
	 * @param buf - the message buffer to add the message to
	 */
	public static FeedbackMessage makeEmpty(BlueberryBuffer buf) {
		FeedbackMessage msg = new FeedbackMessage(buf);
		msg.setupHeader(FEEDBACK_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a FeedbackMessage.
	 * a general purpose message that can convey any number of various sequences to convey trajectories, update responses, or configuration
	 * @param buf - the message buffer to add the message to
	 */
	public static FeedbackMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, FEEDBACK_MESSAGE_KEY)){
			return null;
		}
		FeedbackMessage msg = new FeedbackMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * a general purpose message that can convey any number of various sequences to convey trajectories, update responses, or configuration
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= FEEDBACK_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the channel field
	 * the channel to configure
	 * @param i0 - index of config sequence.
	 */
	public int getConfigChannel(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the channel field
	 * the channel to configure
	 * @param i0 - index of config sequence.
	 * @param channel - the channel to configure
	 */
	public void setConfigChannel(int i0, int channel){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , channel);
	}
	/**
	 * A getter for the unit field
	 * A selection of units for the setpoint.
	 * Mostly just to select between angular units and units that do not loop
	 * For now this is not inteded to stray beyond SI
	 * @param i0 - index of config sequence.
	 */
	public UnitEnum getConfigUnit(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_UNIT_INDEX;
		return UnitEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * A setter for the unit field
	 * A selection of units for the setpoint.
	 * Mostly just to select between angular units and units that do not loop
	 * For now this is not inteded to stray beyond SI
	 * @param i0 - index of config sequence.
	 * @param unit - A selection of units for the setpoint.
	 * Mostly just to select between angular units and units that do not loop
	 * For now this is not inteded to stray beyond SI
	 */
	public void setConfigUnit(int i0, UnitEnum unit){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_UNIT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , unit.getValue());
	}
	/**
	 * A getter for the enable field
	 * enable this channel
	 * @param i0 - index of config sequence.
	 */
	public boolean isConfigEnable(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_ENABLE_INDEX;
		return m_buf.readBit(i , FEEDBACK_MESSAGE_CONFIG_ENABLE_BIT_NUM);
	}
	/**
	 * A setter for the enable field
	 * enable this channel
	 * @param i0 - index of config sequence.
	 * @param enable - enable this channel
	 */
	public void setConfigEnable(int i0, boolean enable){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_ENABLE_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeBit(i , FEEDBACK_MESSAGE_CONFIG_ENABLE_BIT_NUM, enable);
	}
	/**
	 * A getter for the minInput field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigMinInput(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MIN_INPUT_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the minInput field
	 * @param i0 - index of config sequence.
	 * @param minInput
	 */
	public void setConfigMinInput(int i0, double minInput){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MIN_INPUT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , minInput);
	}
	/**
	 * A getter for the maxInput field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigMaxInput(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MAX_INPUT_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the maxInput field
	 * @param i0 - index of config sequence.
	 * @param maxInput
	 */
	public void setConfigMaxInput(int i0, double maxInput){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MAX_INPUT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , maxInput);
	}
	/**
	 * A getter for the minOutput field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigMinOutput(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MIN_OUTPUT_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the minOutput field
	 * @param i0 - index of config sequence.
	 * @param minOutput
	 */
	public void setConfigMinOutput(int i0, double minOutput){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MIN_OUTPUT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , minOutput);
	}
	/**
	 * A getter for the maxOutput field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigMaxOutput(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MAX_OUTPUT_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the maxOutput field
	 * @param i0 - index of config sequence.
	 * @param maxOutput
	 */
	public void setConfigMaxOutput(int i0, double maxOutput){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_MAX_OUTPUT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , maxOutput);
	}
	/**
	 * A getter for the inputType field
	 * Defines where the feedback controller should get its input from
	 * @param i0 - index of config sequence.
	 */
	public PlumbingTypeEnum getConfigInputType(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_INPUT_TYPE_INDEX;
		return PlumbingTypeEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * A setter for the inputType field
	 * Defines where the feedback controller should get its input from
	 * @param i0 - index of config sequence.
	 * @param inputType - Defines where the feedback controller should get its input from
	 */
	public void setConfigInputType(int i0, PlumbingTypeEnum inputType){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_INPUT_TYPE_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , inputType.getValue());
	}
	/**
	 * A getter for the outputType field
	 * Defines where the feedback controller should get its input from
	 * @param i0 - index of config sequence.
	 */
	public PlumbingTypeEnum getConfigOutputType(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_OUTPUT_TYPE_INDEX;
		return PlumbingTypeEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * A setter for the outputType field
	 * Defines where the feedback controller should get its input from
	 * @param i0 - index of config sequence.
	 * @param outputType - Defines where the feedback controller should get its input from
	 */
	public void setConfigOutputType(int i0, PlumbingTypeEnum outputType){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_OUTPUT_TYPE_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , outputType.getValue());
	}
	/**
	 * A getter for the inputChannel field
	 * selects the channel to get the input from of the type specified in the inputType field, only if channel number makes sense
	 * @param i0 - index of config sequence.
	 */
	public int getConfigInputChannel(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_INPUT_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the inputChannel field
	 * selects the channel to get the input from of the type specified in the inputType field, only if channel number makes sense
	 * @param i0 - index of config sequence.
	 * @param inputChannel - selects the channel to get the input from of the type specified in the inputType field, only if channel number makes sense
	 */
	public void setConfigInputChannel(int i0, int inputChannel){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_INPUT_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , inputChannel);
	}
	/**
	 * A getter for the outputChannel field
	 * @param i0 - index of config sequence.
	 */
	public int getConfigOutputChannel(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_OUTPUT_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the outputChannel field
	 * @param i0 - index of config sequence.
	 * @param outputChannel
	 */
	public void setConfigOutputChannel(int i0, int outputChannel){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_OUTPUT_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , outputChannel);
	}
	/**
	 * A getter for the c0 field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigC0(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_C_0_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the c0 field
	 * @param i0 - index of config sequence.
	 * @param c0
	 */
	public void setConfigC0(int i0, double c0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_C_0_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , c0);
	}
	/**
	 * A getter for the c1 field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigC1(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_C_1_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the c1 field
	 * @param i0 - index of config sequence.
	 * @param c1
	 */
	public void setConfigC1(int i0, double c1){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_C_1_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , c1);
	}
	/**
	 * A getter for the c2 field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigC2(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_C_2_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the c2 field
	 * @param i0 - index of config sequence.
	 * @param c2
	 */
	public void setConfigC2(int i0, double c2){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_C_2_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , c2);
	}
	/**
	 * A getter for the d1 field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigD1(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_D_1_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the d1 field
	 * @param i0 - index of config sequence.
	 * @param d1
	 */
	public void setConfigD1(int i0, double d1){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_D_1_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , d1);
	}
	/**
	 * A getter for the d2 field
	 * @param i0 - index of config sequence.
	 */
	public double getConfigD2(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_D_2_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the d2 field
	 * @param i0 - index of config sequence.
	 * @param d2
	 */
	public void setConfigD2(int i0, double d2){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_CONFIG_D_2_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , d2);
	}
	/**
	 * A getter for the channel field
	 * the feedback channel that this payload is to update the trajectories of
	 * @param i0 - index of trajectories sequence.
	 */
	public int getTrajectoriesChannel(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the channel field
	 * the feedback channel that this payload is to update the trajectories of
	 * @param i0 - index of trajectories sequence.
	 * @param channel - the feedback channel that this payload is to update the trajectories of
	 */
	public void setTrajectoriesChannel(int i0, int channel){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , channel);
	}
	/**
	 * A getter for the setpoint field
	 * the target value that the feedback controller should achieve
	 * @param i0 - index of trajectories sequence.
	 */
	public double getTrajectoriesSetpoint(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_SETPOINT_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the setpoint field
	 * the target value that the feedback controller should achieve
	 * @param i0 - index of trajectories sequence.
	 * @param setpoint - the target value that the feedback controller should achieve
	 */
	public void setTrajectoriesSetpoint(int i0, double setpoint){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_SETPOINT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , setpoint);
	}
	/**
	 * A getter for the setpointRate field
	 * the target rate of setpoint change that should be achieved when the setpoint is achieved
	 * @param i0 - index of trajectories sequence.
	 */
	public double getTrajectoriesSetpointRate(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_SETPOINT_RATE_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the setpointRate field
	 * the target rate of setpoint change that should be achieved when the setpoint is achieved
	 * @param i0 - index of trajectories sequence.
	 * @param setpointRate - the target rate of setpoint change that should be achieved when the setpoint is achieved
	 */
	public void setTrajectoriesSetpointRate(int i0, double setpointRate){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_SETPOINT_RATE_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , setpointRate);
	}
	/**
	 * A getter for the time field
	 * the time by which the setpoint and setpoint rate should be acheived. This is in milliseconds of "host time"
	 * @param i0 - index of trajectories sequence.
	 */
	public long getTrajectoriesTime(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_TIME_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * A setter for the time field
	 * the time by which the setpoint and setpoint rate should be acheived. This is in milliseconds of "host time"
	 * @param i0 - index of trajectories sequence.
	 * @param time - the time by which the setpoint and setpoint rate should be acheived. This is in milliseconds of "host time"
	 */
	public void setTrajectoriesTime(int i0, long time){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_TIME_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint32(i , time);
	}
	/**
	 * A getter for the channel field
	 * @param i0 - index of response sequence.
	 */
	public int getResponseChannel(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the channel field
	 * @param i0 - index of response sequence.
	 * @param channel
	 */
	public void setResponseChannel(int i0, int channel){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , channel);
	}
	/**
	 * A getter for the actual field
	 * @param i0 - index of response sequence.
	 */
	public double getResponseActual(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_ACTUAL_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the actual field
	 * @param i0 - index of response sequence.
	 * @param actual
	 */
	public void setResponseActual(int i0, double actual){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_ACTUAL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , actual);
	}
	/**
	 * A getter for the setpoint field
	 * @param i0 - index of response sequence.
	 */
	public double getResponseSetpoint(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_SETPOINT_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the setpoint field
	 * @param i0 - index of response sequence.
	 * @param setpoint
	 */
	public void setResponseSetpoint(int i0, double setpoint){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_SETPOINT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , setpoint);
	}
	/**
	 * A getter for the output field
	 * @param i0 - index of response sequence.
	 */
	public double getResponseOutput(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_OUTPUT_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the output field
	 * @param i0 - index of response sequence.
	 * @param output
	 */
	public void setResponseOutput(int i0, double output){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_OUTPUT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , output);
	}
	/**
	 * A getter for the queueLength field
	 * the number of items in the queue
	 * @param i0 - index of response sequence.
	 */
	public int getResponseQueueLength(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_QUEUE_LENGTH_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the queueLength field
	 * the number of items in the queue
	 * @param i0 - index of response sequence.
	 * @param queueLength - the number of items in the queue
	 */
	public void setResponseQueueLength(int i0, int queueLength){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_QUEUE_LENGTH_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , queueLength);
	}
	/**
	 * A getter for the endTime field
	 * the time when the last trajectory in the queue will end
	 * @param i0 - index of response sequence.
	 */
	public long getResponseEndTime(int i0){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_END_TIME_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * A setter for the endTime field
	 * the time when the last trajectory in the queue will end
	 * @param i0 - index of response sequence.
	 * @param endTime - the time when the last trajectory in the queue will end
	 */
	public void setResponseEndTime(int i0, long endTime){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + FEEDBACK_MESSAGE_RESPONSE_END_TIME_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint32(i , endTime);
	}
	/**
	 * A function to initialize a Config Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initConfig(int n){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Config Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getConfigSequenceLength(){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
	/**
	 * A function to initialize a Trajectory Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initTrajectories(int n){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Trajectory Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getTrajectoriesSequenceLength(){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_TRAJECTORIES_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
	/**
	 * A function to initialize a Response Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initResponse(int n){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Response Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getResponseSequenceLength(){
		int i = 0;
		i = i + FEEDBACK_MESSAGE_RESPONSE_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
