/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a FlashProgramMessage
 */
public class FlashProgramMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int FLASH_PROGRAM_MESSAGE_MAX_ORDINAL = 9;

	private static final int FLASH_PROGRAM_MESSAGE_LENGTH = 36;

	//These values are used to index into this message to access the various fields.
	private static final int FLASH_PROGRAM_MESSAGE_COUNT_INDEX = 28;
	private static final int FLASH_PROGRAM_MESSAGE_CRC_INDEX = 16;
	private static final int FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_INDEX = 32;
	private static final int FLASH_PROGRAM_MESSAGE_END_INDEX = 24;
	private static final int FLASH_PROGRAM_MESSAGE_START_INDEX = 20;
	private static final int FLASH_PROGRAM_MESSAGE_STATE_INDEX = 8;
	private static final int FLASH_PROGRAM_MESSAGE_VERSION_INDEX = 12;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int FLASH_PROGRAM_MESSAGE_COUNT_ORDINAL = 8;
	private static final int FLASH_PROGRAM_MESSAGE_CRC_ORDINAL = 5;
	private static final int FLASH_PROGRAM_MESSAGE_END_ORDINAL = 7;
	private static final int FLASH_PROGRAM_MESSAGE_START_ORDINAL = 6;
	private static final int FLASH_PROGRAM_MESSAGE_STATE_ORDINAL = 3;
	private static final int FLASH_PROGRAM_MESSAGE_VERSION_ORDINAL = 4;

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 4;
	/**
	 * A constructor to create a FlashProgramMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * a message to convey flash programming data
	 * @param buf - the message buffer to add the message to
	 */
	private FlashProgramMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a FlashProgramMessage for transmission.
	 * a message to convey flash programming data
	 * @param buf - the message buffer to add the message to
	 * @param state
	 * @param version
	 * @param crc - a crc of the words sent so far. This is an ethernet CRC-32
	 * @param start - the number of words transferred so far, and the start index of the next array of data. Peripherals will indicate the total words that have passed CRC here.
	 * @param end - the number of words that will have been transferred after the following array. This is also the index of the first element of the array after this one. Peripherals will indicate the total number of words received here.
	 * @param count - the total number of words that will be transferred. When count equals total length then the transfer is complete
	 */
	public static FlashProgramMessage make(BlueberryBuffer buf, FlashProgramStateEnum state, long version, long crc, long start, long end, long count) {
		FlashProgramMessage msg = new FlashProgramMessage(buf);
		msg.setupHeader(FLASH_PROGRAM_MESSAGE_KEY, FLASH_PROGRAM_MESSAGE_MAX_ORDINAL, FLASH_PROGRAM_MESSAGE_LENGTH);
		msg.m_buf.writeUint8(FLASH_PROGRAM_MESSAGE_STATE_INDEX, state.getValue());
		msg.m_buf.writeUint32(FLASH_PROGRAM_MESSAGE_VERSION_INDEX, version);
		msg.m_buf.writeUint32(FLASH_PROGRAM_MESSAGE_CRC_INDEX, crc);
		msg.m_buf.writeUint32(FLASH_PROGRAM_MESSAGE_START_INDEX, start);
		msg.m_buf.writeUint32(FLASH_PROGRAM_MESSAGE_END_INDEX, end);
		msg.m_buf.writeUint32(FLASH_PROGRAM_MESSAGE_COUNT_INDEX, count);
		msg.m_buf.writeUint16(FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty FlashProgramMessage for transmission.
	 * a message to convey flash programming data
	 * @param buf - the message buffer to add the message to
	 */
	public static FlashProgramMessage makeEmpty(BlueberryBuffer buf) {
		FlashProgramMessage msg = new FlashProgramMessage(buf);
		msg.setupHeader(FLASH_PROGRAM_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a FlashProgramMessage.
	 * a message to convey flash programming data
	 * @param buf - the message buffer to add the message to
	 */
	public static FlashProgramMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, FLASH_PROGRAM_MESSAGE_KEY)){
			return null;
		}
		FlashProgramMessage msg = new FlashProgramMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * a message to convey flash programming data
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= FLASH_PROGRAM_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the state field
	 */
	public FlashProgramStateEnum getState(){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_STATE_INDEX;
		return FlashProgramStateEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the state field
	 */
	boolean isStatePresent(){
		return FLASH_PROGRAM_MESSAGE_STATE_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the version field
	 */
	public long getVersion(){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_VERSION_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the version field
	 */
	boolean isVersionPresent(){
		return FLASH_PROGRAM_MESSAGE_VERSION_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the crc field
	 * a crc of the words sent so far. This is an ethernet CRC-32
	 */
	public long getCrc(){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_CRC_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the crc field
	 * a crc of the words sent so far. This is an ethernet CRC-32
	 */
	boolean isCrcPresent(){
		return FLASH_PROGRAM_MESSAGE_CRC_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the start field
	 * the number of words transferred so far, and the start index of the next array of data. Peripherals will indicate the total words that have passed CRC here.
	 */
	public long getStart(){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_START_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the start field
	 * the number of words transferred so far, and the start index of the next array of data. Peripherals will indicate the total words that have passed CRC here.
	 */
	boolean isStartPresent(){
		return FLASH_PROGRAM_MESSAGE_START_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the end field
	 * the number of words that will have been transferred after the following array. This is also the index of the first element of the array after this one. Peripherals will indicate the total number of words received here.
	 */
	public long getEnd(){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_END_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the end field
	 * the number of words that will have been transferred after the following array. This is also the index of the first element of the array after this one. Peripherals will indicate the total number of words received here.
	 */
	boolean isEndPresent(){
		return FLASH_PROGRAM_MESSAGE_END_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the count field
	 * the total number of words that will be transferred. When count equals total length then the transfer is complete
	 */
	public long getCount(){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_COUNT_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the count field
	 * the total number of words that will be transferred. When count equals total length then the transfer is complete
	 */
	boolean isCountPresent(){
		return FLASH_PROGRAM_MESSAGE_COUNT_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the data field
	 * @param i0 - index of data sequence.
	 */
	public long getData(int i0){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		return m_buf.readUint32(i );
	}
	/**
	 * A setter for the data field
	 * @param i0 - index of data sequence.
	 * @param data
	 */
	public void setData(int i0, long data){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint32(i , data);
	}
	/**
	 * A function to initialize a Flash Program Sequence
	 * an array of 32 bit words of data. A series of these payloads sent over time will make up the total new firmware
	 * the data corresponds to the words to write to flash
	 * @param n - the number of elements of this sequence
	 */
	public void initData(int n){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Flash Program Sequence
	 * an array of 32 bit words of data. A series of these payloads sent over time will make up the total new firmware
	 * the data corresponds to the words to write to flash
	 * @return - the number of elements in the sequence
	 */
	public int getDataSequenceLength(){
		int i = 0;
		i = i + FLASH_PROGRAM_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
