/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a GpioPinsMessage
 */
public class GpioPinsMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int GPIO_PINS_MESSAGE_MAX_ORDINAL = 3;

	private static final int GPIO_PINS_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 2;
	/**
	 * A constructor to create a GpioPinsMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey the digital values of each GPIO pin
	 * Each element in the sequence is the pin values of a port: Port A, Port B ... Port N
	 * @param buf - the message buffer to add the message to
	 */
	private GpioPinsMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a GpioPinsMessage for transmission.
	 * A message to convey the digital values of each GPIO pin
	 * Each element in the sequence is the pin values of a port: Port A, Port B ... Port N
	 * @param buf - the message buffer to add the message to
	 */
	public static GpioPinsMessage make(BlueberryBuffer buf) {
		GpioPinsMessage msg = new GpioPinsMessage(buf);
		msg.setupHeader(GPIO_PINS_MESSAGE_KEY, GPIO_PINS_MESSAGE_MAX_ORDINAL, GPIO_PINS_MESSAGE_LENGTH);
		msg.m_buf.writeUint16(GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty GpioPinsMessage for transmission.
	 * A message to convey the digital values of each GPIO pin
	 * Each element in the sequence is the pin values of a port: Port A, Port B ... Port N
	 * @param buf - the message buffer to add the message to
	 */
	public static GpioPinsMessage makeEmpty(BlueberryBuffer buf) {
		GpioPinsMessage msg = new GpioPinsMessage(buf);
		msg.setupHeader(GPIO_PINS_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a GpioPinsMessage.
	 * A message to convey the digital values of each GPIO pin
	 * Each element in the sequence is the pin values of a port: Port A, Port B ... Port N
	 * @param buf - the message buffer to add the message to
	 */
	public static GpioPinsMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, GPIO_PINS_MESSAGE_KEY)){
			return null;
		}
		GpioPinsMessage msg = new GpioPinsMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey the digital values of each GPIO pin
	 * Each element in the sequence is the pin values of a port: Port A, Port B ... Port N
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= GPIO_PINS_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the port field
	 * @param i0 - index of port sequence.
	 */
	public int getPort(int i0){
		int i = 0;
		i = i + GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		return m_buf.readUint16(i );
	}
	/**
	 * A setter for the port field
	 * @param i0 - index of port sequence.
	 * @param port
	 */
	public void setPort(int i0, int port){
		int i = 0;
		i = i + GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint16(i , port);
	}
	/**
	 * A function to initialize a Port Pins
	 * @param n - the number of elements of this sequence
	 */
	public void initPort(int n){
		int i = 0;
		i = i + GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Port Pins
	 * @return - the number of elements in the sequence
	 */
	public int getPortSequenceLength(){
		int i = 0;
		i = i + GPIO_PINS_MESSAGE_PORT_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
