/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a GpioConfigMessage
 */
public class GpioConfigMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int GPIO_CONFIG_MESSAGE_MAX_ORDINAL = 3;

	private static final int GPIO_CONFIG_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int GPIO_CONFIG_MESSAGE_PIN_CONFIGS_DIR_INDEX = 1;
	private static final int GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PIN_INDEX = 0;
	private static final int GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 2;
	/**
	 * A constructor to create a GpioConfigMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	private GpioConfigMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a GpioConfigMessage for transmission.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static GpioConfigMessage make(BlueberryBuffer buf) {
		GpioConfigMessage msg = new GpioConfigMessage(buf);
		msg.setupHeader(GPIO_CONFIG_MESSAGE_KEY, GPIO_CONFIG_MESSAGE_MAX_ORDINAL, GPIO_CONFIG_MESSAGE_LENGTH);
		msg.m_buf.writeUint16(GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty GpioConfigMessage for transmission.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static GpioConfigMessage makeEmpty(BlueberryBuffer buf) {
		GpioConfigMessage msg = new GpioConfigMessage(buf);
		msg.setupHeader(GPIO_CONFIG_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a GpioConfigMessage.
	 * A message to convey config parameters for ADCs
	 * @param buf - the message buffer to add the message to
	 */
	public static GpioConfigMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, GPIO_CONFIG_MESSAGE_KEY)){
			return null;
		}
		GpioConfigMessage msg = new GpioConfigMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey config parameters for ADCs
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= GPIO_CONFIG_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the pin field
	 * this is formed from the Port in the top nibble and the pin in the least significant nibble
	 * @param i0 - index of pinConfigs sequence.
	 */
	public int getPinConfigsPin(int i0){
		int i = 0;
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PIN_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the pin field
	 * this is formed from the Port in the top nibble and the pin in the least significant nibble
	 * @param i0 - index of pinConfigs sequence.
	 * @param pin - this is formed from the Port in the top nibble and the pin in the least significant nibble
	 */
	public void setPinConfigsPin(int i0, int pin){
		int i = 0;
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PIN_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , pin);
	}
	/**
	 * A getter for the dir field
	 * @param i0 - index of pinConfigs sequence.
	 */
	public GpioDirEnum getPinConfigsDir(int i0){
		int i = 0;
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_DIR_INDEX;
		return GpioDirEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * A setter for the dir field
	 * @param i0 - index of pinConfigs sequence.
	 * @param dir
	 */
	public void setPinConfigsDir(int i0, GpioDirEnum dir){
		int i = 0;
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_DIR_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , dir.getValue());
	}
	/**
	 * A function to initialize a Gpio Pin Config Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initPinConfigs(int n){
		int i = 0;
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Gpio Pin Config Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getPinConfigsSequenceLength(){
		int i = 0;
		i = i + GPIO_CONFIG_MESSAGE_PIN_CONFIGS_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
