/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a I2CTransactionMessage
 */
public class I2CTransactionMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int I_2_C_TRANSACTION_MESSAGE_MAX_ORDINAL = 8;

	private static final int I_2_C_TRANSACTION_MESSAGE_LENGTH = 24;

	//These values are used to index into this message to access the various fields.
	private static final int I_2_C_TRANSACTION_MESSAGE_I_2_C_ADDR_INDEX = 9;
	private static final int I_2_C_TRANSACTION_MESSAGE_I_2_C_DEV_INDEX = 8;
	private static final int I_2_C_TRANSACTION_MESSAGE_NUM_RX_BYTES_INDEX = 12;
	private static final int I_2_C_TRANSACTION_MESSAGE_NUM_TX_BYTES_INDEX = 10;
	private static final int I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX = 20;
	private static final int I_2_C_TRANSACTION_MESSAGE_TRANSACTION_ID_INDEX = 16;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int I_2_C_TRANSACTION_MESSAGE_I_2_C_ADDR_ORDINAL = 4;
	private static final int I_2_C_TRANSACTION_MESSAGE_I_2_C_DEV_ORDINAL = 3;
	private static final int I_2_C_TRANSACTION_MESSAGE_NUM_RX_BYTES_ORDINAL = 6;
	private static final int I_2_C_TRANSACTION_MESSAGE_NUM_TX_BYTES_ORDINAL = 5;
	private static final int I_2_C_TRANSACTION_MESSAGE_TRANSACTION_ID_ORDINAL = 7;

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 4;
	/**
	 * A constructor to create a I2CTransactionMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 *  A message to define an I2C transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 */
	private I2CTransactionMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a I2CTransactionMessage for transmission.
	 *  A message to define an I2C transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 * @param i2CDev
	 * @param i2CAddr
	 * @param numTxBytes
	 * @param numRxBytes
	 * @param transactionId -  Unique ID for the transaction
	 */
	public static I2CTransactionMessage make(BlueberryBuffer buf, I2CDevBbEnum i2CDev, int i2CAddr, int numTxBytes, int numRxBytes, int transactionId) {
		I2CTransactionMessage msg = new I2CTransactionMessage(buf);
		msg.setupHeader(I_2_C_TRANSACTION_MESSAGE_KEY, I_2_C_TRANSACTION_MESSAGE_MAX_ORDINAL, I_2_C_TRANSACTION_MESSAGE_LENGTH);
		msg.m_buf.writeUint8(I_2_C_TRANSACTION_MESSAGE_I_2_C_DEV_INDEX, i2CDev.getValue());
		msg.m_buf.writeUint8(I_2_C_TRANSACTION_MESSAGE_I_2_C_ADDR_INDEX, i2CAddr);
		msg.m_buf.writeUint16(I_2_C_TRANSACTION_MESSAGE_NUM_TX_BYTES_INDEX, numTxBytes);
		msg.m_buf.writeUint16(I_2_C_TRANSACTION_MESSAGE_NUM_RX_BYTES_INDEX, numRxBytes);
		msg.m_buf.writeInt32(I_2_C_TRANSACTION_MESSAGE_TRANSACTION_ID_INDEX, transactionId);
		msg.m_buf.writeUint16(I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty I2CTransactionMessage for transmission.
	 *  A message to define an I2C transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 */
	public static I2CTransactionMessage makeEmpty(BlueberryBuffer buf) {
		I2CTransactionMessage msg = new I2CTransactionMessage(buf);
		msg.setupHeader(I_2_C_TRANSACTION_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a I2CTransactionMessage.
	 *  A message to define an I2C transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 */
	public static I2CTransactionMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, I_2_C_TRANSACTION_MESSAGE_KEY)){
			return null;
		}
		I2CTransactionMessage msg = new I2CTransactionMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 *  A message to define an I2C transaction to be sent out
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= I_2_C_TRANSACTION_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the i2CDev field
	 */
	public I2CDevBbEnum getI2CDev(){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_I_2_C_DEV_INDEX;
		return I2CDevBbEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the i2CDev field
	 */
	boolean isI2CDevPresent(){
		return I_2_C_TRANSACTION_MESSAGE_I_2_C_DEV_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the i2CAddr field
	 */
	public int getI2CAddr(){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_I_2_C_ADDR_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * Tests if the current message containts the i2CAddr field
	 */
	boolean isI2CAddrPresent(){
		return I_2_C_TRANSACTION_MESSAGE_I_2_C_ADDR_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the numTxBytes field
	 */
	public int getNumTxBytes(){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_NUM_TX_BYTES_INDEX;
		return m_buf.readUint16(i );
	}
	/**
	 * Tests if the current message containts the numTxBytes field
	 */
	boolean isNumTxBytesPresent(){
		return I_2_C_TRANSACTION_MESSAGE_NUM_TX_BYTES_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the numRxBytes field
	 */
	public int getNumRxBytes(){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_NUM_RX_BYTES_INDEX;
		return m_buf.readUint16(i );
	}
	/**
	 * Tests if the current message containts the numRxBytes field
	 */
	boolean isNumRxBytesPresent(){
		return I_2_C_TRANSACTION_MESSAGE_NUM_RX_BYTES_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the transactionId field
	 *  Unique ID for the transaction
	 */
	public int getTransactionId(){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_TRANSACTION_ID_INDEX;
		return m_buf.readInt32(i );
	}
	/**
	 * Tests if the current message containts the transactionId field
	 *  Unique ID for the transaction
	 */
	boolean isTransactionIdPresent(){
		return I_2_C_TRANSACTION_MESSAGE_TRANSACTION_ID_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the transactionData field
	 * @param i0 - index of transactionData sequence.
	 */
	public long getTransactionData(int i0){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		return m_buf.readUint32(i );
	}
	/**
	 * A setter for the transactionData field
	 * @param i0 - index of transactionData sequence.
	 * @param transactionData
	 */
	public void setTransactionData(int i0, long transactionData){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint32(i , transactionData);
	}
	/**
	 * A function to initialize a I 2 C Transaction Data
	 * @param n - the number of elements of this sequence
	 */
	public void initTransactionData(int n){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence I 2 C Transaction Data
	 * @return - the number of elements in the sequence
	 */
	public int getTransactionDataSequenceLength(){
		int i = 0;
		i = i + I_2_C_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
