/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a IdMessage
 */
public class IdMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int ID_MESSAGE_MAX_ORDINAL = 3;

	private static final int ID_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int ID_MESSAGE_ID_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int ID_MESSAGE_ID_ORDINAL = 3;

	//Bit Nums
	/**
	 * A constructor to create a IdMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 */
	private IdMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a IdMessage for transmission.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 * @param id - the id of this device
	 * this is unique.
	 */
	public static IdMessage make(BlueberryBuffer buf, long id) {
		IdMessage msg = new IdMessage(buf);
		msg.setupHeader(ID_MESSAGE_KEY, ID_MESSAGE_MAX_ORDINAL, ID_MESSAGE_LENGTH);
		msg.m_buf.writeUint32(ID_MESSAGE_ID_INDEX, id);
		return msg;
	}
	/**
	 * A constructor to create an empty IdMessage for transmission.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 */
	public static IdMessage makeEmpty(BlueberryBuffer buf) {
		IdMessage msg = new IdMessage(buf);
		msg.setupHeader(ID_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a IdMessage.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 */
	public static IdMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, ID_MESSAGE_KEY)){
			return null;
		}
		IdMessage msg = new IdMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey the unique ID of this devices
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= ID_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the id field
	 * the id of this device
	 * this is unique.
	 */
	public long getId(){
		int i = 0;
		i = i + ID_MESSAGE_ID_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the id field
	 * the id of this device
	 * this is unique.
	 */
	boolean isIdPresent(){
		return ID_MESSAGE_ID_ORDINAL <= (getMaxOrdinal());
	}
}
