/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a ImuDataMessage
 */
public class ImuDataMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int IMU_DATA_MESSAGE_MAX_ORDINAL = 3;

	private static final int IMU_DATA_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX = 8;
	private static final int IMU_DATA_MESSAGE_COORDS_TIME_INDEX = 16;
	private static final int IMU_DATA_MESSAGE_COORDS_UNIT_INDEX = 12;
	private static final int IMU_DATA_MESSAGE_COORDS_X_INDEX = 0;
	private static final int IMU_DATA_MESSAGE_COORDS_Y_INDEX = 4;
	private static final int IMU_DATA_MESSAGE_COORDS_Z_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 24;
	/**
	 * A constructor to create a ImuDataMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey one or more coordinates
	 * @param buf - the message buffer to add the message to
	 */
	private ImuDataMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a ImuDataMessage for transmission.
	 * A message to convey one or more coordinates
	 * @param buf - the message buffer to add the message to
	 */
	public static ImuDataMessage make(BlueberryBuffer buf) {
		ImuDataMessage msg = new ImuDataMessage(buf);
		msg.setupHeader(IMU_DATA_MESSAGE_KEY, IMU_DATA_MESSAGE_MAX_ORDINAL, IMU_DATA_MESSAGE_LENGTH);
		msg.m_buf.writeUint16(IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty ImuDataMessage for transmission.
	 * A message to convey one or more coordinates
	 * @param buf - the message buffer to add the message to
	 */
	public static ImuDataMessage makeEmpty(BlueberryBuffer buf) {
		ImuDataMessage msg = new ImuDataMessage(buf);
		msg.setupHeader(IMU_DATA_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a ImuDataMessage.
	 * A message to convey one or more coordinates
	 * @param buf - the message buffer to add the message to
	 */
	public static ImuDataMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, IMU_DATA_MESSAGE_KEY)){
			return null;
		}
		ImuDataMessage msg = new ImuDataMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey one or more coordinates
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= IMU_DATA_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the x field
	 * @param i0 - index of coords sequence.
	 */
	public double getCoordsX(int i0){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_X_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the x field
	 * @param i0 - index of coords sequence.
	 * @param x
	 */
	public void setCoordsX(int i0, double x){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_X_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , x);
	}
	/**
	 * A getter for the y field
	 * @param i0 - index of coords sequence.
	 */
	public double getCoordsY(int i0){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_Y_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the y field
	 * @param i0 - index of coords sequence.
	 * @param y
	 */
	public void setCoordsY(int i0, double y){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_Y_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , y);
	}
	/**
	 * A getter for the z field
	 * @param i0 - index of coords sequence.
	 */
	public double getCoordsZ(int i0){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_Z_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the z field
	 * @param i0 - index of coords sequence.
	 * @param z
	 */
	public void setCoordsZ(int i0, double z){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_Z_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , z);
	}
	/**
	 * A getter for the unit field
	 * A selection of units for the setpoint.
	 * Mostly just to select between angular units and units that do not loop
	 * For now this is not inteded to stray beyond SI
	 * @param i0 - index of coords sequence.
	 */
	public UnitEnum getCoordsUnit(int i0){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_UNIT_INDEX;
		return UnitEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * A setter for the unit field
	 * A selection of units for the setpoint.
	 * Mostly just to select between angular units and units that do not loop
	 * For now this is not inteded to stray beyond SI
	 * @param i0 - index of coords sequence.
	 * @param unit - A selection of units for the setpoint.
	 * Mostly just to select between angular units and units that do not loop
	 * For now this is not inteded to stray beyond SI
	 */
	public void setCoordsUnit(int i0, UnitEnum unit){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_UNIT_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , unit.getValue());
	}
	/**
	 * A getter for the time field
	 * a measure of time in 100ns increments since an epoch of January 1st 2000
	 * @param i0 - index of coords sequence.
	 */
	public long getCoordsTime(int i0){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_TIME_INDEX;
		return m_buf.readUint64(i );
	}
	/**
	 * A setter for the time field
	 * a measure of time in 100ns increments since an epoch of January 1st 2000
	 * @param i0 - index of coords sequence.
	 * @param time - a measure of time in 100ns increments since an epoch of January 1st 2000
	 */
	public void setCoordsTime(int i0, long time){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + IMU_DATA_MESSAGE_COORDS_TIME_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint64(i , time);
	}
	/**
	 * A function to initialize a Coordinates
	 * @param n - the number of elements of this sequence
	 */
	public void initCoords(int n){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Coordinates
	 * @return - the number of elements in the sequence
	 */
	public int getCoordsSequenceLength(){
		int i = 0;
		i = i + IMU_DATA_MESSAGE_COORDS_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
