/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a OscopeConfigMessage
 */
public class OscopeConfigMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int OSCOPE_CONFIG_MESSAGE_MAX_ORDINAL = 8;

	private static final int OSCOPE_CONFIG_MESSAGE_LENGTH = 24;

	//These values are used to index into this message to access the various fields.
	private static final int OSCOPE_CONFIG_MESSAGE_HOLDOFF_INDEX = 20;
	private static final int OSCOPE_CONFIG_MESSAGE_PERIOD_INDEX = 8;
	private static final int OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_INDEX = 14;
	private static final int OSCOPE_CONFIG_MESSAGE_THRESHOLD_INDEX = 16;
	private static final int OSCOPE_CONFIG_MESSAGE_TRIGGER_SOURCE_INDEX = 12;
	private static final int OSCOPE_CONFIG_MESSAGE_TRIG_POS_INDEX = 13;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int OSCOPE_CONFIG_MESSAGE_HOLDOFF_ORDINAL = 6;
	private static final int OSCOPE_CONFIG_MESSAGE_PERIOD_ORDINAL = 3;
	private static final int OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_ORDINAL = 8;
	private static final int OSCOPE_CONFIG_MESSAGE_THRESHOLD_ORDINAL = 5;
	private static final int OSCOPE_CONFIG_MESSAGE_TRIGGER_SOURCE_ORDINAL = 4;
	private static final int OSCOPE_CONFIG_MESSAGE_TRIG_POS_ORDINAL = 7;

	//Bit Nums
	private static final int OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_BIT_NUM = 0;
	/**
	 * A constructor to create a OscopeConfigMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey setup parameters for the oscope module
	 * @param buf - the message buffer to add the message to
	 */
	private OscopeConfigMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a OscopeConfigMessage for transmission.
	 * A message to convey setup parameters for the oscope module
	 * @param buf - the message buffer to add the message to
	 * @param period - the sample period in seconds of the oscope
	 * @param triggerSource - a sinksource that the trigger is derived from
	 * @param threshold - the threshold measurement for the trigger
	 * @param holdoff - the delay before triggering again
	 * @param trigPos
	 * @param risingNotFalling - triggers on rising edge of trigger if true, else falling
	 */
	public static OscopeConfigMessage make(BlueberryBuffer buf, double period, int triggerSource, double threshold, double holdoff, TriggerPosEnum trigPos, boolean risingNotFalling) {
		OscopeConfigMessage msg = new OscopeConfigMessage(buf);
		msg.setupHeader(OSCOPE_CONFIG_MESSAGE_KEY, OSCOPE_CONFIG_MESSAGE_MAX_ORDINAL, OSCOPE_CONFIG_MESSAGE_LENGTH);
		msg.m_buf.writeFloat32(OSCOPE_CONFIG_MESSAGE_PERIOD_INDEX, period);
		msg.m_buf.writeUint8(OSCOPE_CONFIG_MESSAGE_TRIGGER_SOURCE_INDEX, triggerSource);
		msg.m_buf.writeFloat32(OSCOPE_CONFIG_MESSAGE_THRESHOLD_INDEX, threshold);
		msg.m_buf.writeFloat32(OSCOPE_CONFIG_MESSAGE_HOLDOFF_INDEX, holdoff);
		msg.m_buf.writeUint8(OSCOPE_CONFIG_MESSAGE_TRIG_POS_INDEX, trigPos.getValue());
		msg.m_buf.writeBit(OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_INDEX, OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_BIT_NUM, risingNotFalling);
		return msg;
	}
	/**
	 * A constructor to create an empty OscopeConfigMessage for transmission.
	 * A message to convey setup parameters for the oscope module
	 * @param buf - the message buffer to add the message to
	 */
	public static OscopeConfigMessage makeEmpty(BlueberryBuffer buf) {
		OscopeConfigMessage msg = new OscopeConfigMessage(buf);
		msg.setupHeader(OSCOPE_CONFIG_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a OscopeConfigMessage.
	 * A message to convey setup parameters for the oscope module
	 * @param buf - the message buffer to add the message to
	 */
	public static OscopeConfigMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, OSCOPE_CONFIG_MESSAGE_KEY)){
			return null;
		}
		OscopeConfigMessage msg = new OscopeConfigMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey setup parameters for the oscope module
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= OSCOPE_CONFIG_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the period field
	 * the sample period in seconds of the oscope
	 */
	public double getPeriod(){
		int i = 0;
		i = i + OSCOPE_CONFIG_MESSAGE_PERIOD_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the period field
	 * the sample period in seconds of the oscope
	 */
	boolean isPeriodPresent(){
		return OSCOPE_CONFIG_MESSAGE_PERIOD_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the triggerSource field
	 * a sinksource that the trigger is derived from
	 */
	public int getTriggerSource(){
		int i = 0;
		i = i + OSCOPE_CONFIG_MESSAGE_TRIGGER_SOURCE_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * Tests if the current message containts the triggerSource field
	 * a sinksource that the trigger is derived from
	 */
	boolean isTriggerSourcePresent(){
		return OSCOPE_CONFIG_MESSAGE_TRIGGER_SOURCE_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the threshold field
	 * the threshold measurement for the trigger
	 */
	public double getThreshold(){
		int i = 0;
		i = i + OSCOPE_CONFIG_MESSAGE_THRESHOLD_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the threshold field
	 * the threshold measurement for the trigger
	 */
	boolean isThresholdPresent(){
		return OSCOPE_CONFIG_MESSAGE_THRESHOLD_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the holdoff field
	 * the delay before triggering again
	 */
	public double getHoldoff(){
		int i = 0;
		i = i + OSCOPE_CONFIG_MESSAGE_HOLDOFF_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the holdoff field
	 * the delay before triggering again
	 */
	boolean isHoldoffPresent(){
		return OSCOPE_CONFIG_MESSAGE_HOLDOFF_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the trigPos field
	 */
	public TriggerPosEnum getTrigPos(){
		int i = 0;
		i = i + OSCOPE_CONFIG_MESSAGE_TRIG_POS_INDEX;
		return TriggerPosEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the trigPos field
	 */
	boolean isTrigPosPresent(){
		return OSCOPE_CONFIG_MESSAGE_TRIG_POS_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the risingNotFalling field
	 * triggers on rising edge of trigger if true, else falling
	 */
	public boolean isRisingNotFalling(){
		int i = 0;
		i = i + OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_INDEX;
		return m_buf.readBit(i , OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_BIT_NUM);
	}
	/**
	 * Tests if the current message containts the risingNotFalling field
	 * triggers on rising edge of trigger if true, else falling
	 */
	boolean isRisingNotFallingPresent(){
		return OSCOPE_CONFIG_MESSAGE_RISING_NOT_FALLING_ORDINAL <= (getMaxOrdinal());
	}
}
