/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a OscopeDataMessage
 */
public class OscopeDataMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int OSCOPE_DATA_MESSAGE_MAX_ORDINAL = 8;

	private static final int OSCOPE_DATA_MESSAGE_LENGTH = 28;

	//These values are used to index into this message to access the various fields.
	private static final int OSCOPE_DATA_MESSAGE_CAPTURE_ID_INDEX = 12;
	private static final int OSCOPE_DATA_MESSAGE_CHANNEL_INDEX = 8;
	private static final int OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX = 24;
	private static final int OSCOPE_DATA_MESSAGE_GAIN_INDEX = 16;
	private static final int OSCOPE_DATA_MESSAGE_OFFSET_INDEX = 20;
	private static final int OSCOPE_DATA_MESSAGE_SOURCE_INDEX = 9;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int OSCOPE_DATA_MESSAGE_CAPTURE_ID_ORDINAL = 4;
	private static final int OSCOPE_DATA_MESSAGE_CHANNEL_ORDINAL = 3;
	private static final int OSCOPE_DATA_MESSAGE_GAIN_ORDINAL = 5;
	private static final int OSCOPE_DATA_MESSAGE_OFFSET_ORDINAL = 6;
	private static final int OSCOPE_DATA_MESSAGE_SOURCE_ORDINAL = 7;

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 1;
	/**
	 * A constructor to create a OscopeDataMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * a message to convey a single channel of oscope data
	 * this can also be used to configure a channel - data would be zero length in that case
	 * @param buf - the message buffer to add the message to
	 */
	private OscopeDataMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a OscopeDataMessage for transmission.
	 * a message to convey a single channel of oscope data
	 * this can also be used to configure a channel - data would be zero length in that case
	 * @param buf - the message buffer to add the message to
	 * @param channel
	 * @param captureId
	 * @param gain
	 * @param offset
	 * @param source - sink-source that data is captured from
	 */
	public static OscopeDataMessage make(BlueberryBuffer buf, int channel, long captureId, double gain, double offset, int source) {
		OscopeDataMessage msg = new OscopeDataMessage(buf);
		msg.setupHeader(OSCOPE_DATA_MESSAGE_KEY, OSCOPE_DATA_MESSAGE_MAX_ORDINAL, OSCOPE_DATA_MESSAGE_LENGTH);
		msg.m_buf.writeUint8(OSCOPE_DATA_MESSAGE_CHANNEL_INDEX, channel);
		msg.m_buf.writeUint32(OSCOPE_DATA_MESSAGE_CAPTURE_ID_INDEX, captureId);
		msg.m_buf.writeFloat32(OSCOPE_DATA_MESSAGE_GAIN_INDEX, gain);
		msg.m_buf.writeFloat32(OSCOPE_DATA_MESSAGE_OFFSET_INDEX, offset);
		msg.m_buf.writeUint8(OSCOPE_DATA_MESSAGE_SOURCE_INDEX, source);
		msg.m_buf.writeUint16(OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty OscopeDataMessage for transmission.
	 * a message to convey a single channel of oscope data
	 * this can also be used to configure a channel - data would be zero length in that case
	 * @param buf - the message buffer to add the message to
	 */
	public static OscopeDataMessage makeEmpty(BlueberryBuffer buf) {
		OscopeDataMessage msg = new OscopeDataMessage(buf);
		msg.setupHeader(OSCOPE_DATA_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a OscopeDataMessage.
	 * a message to convey a single channel of oscope data
	 * this can also be used to configure a channel - data would be zero length in that case
	 * @param buf - the message buffer to add the message to
	 */
	public static OscopeDataMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, OSCOPE_DATA_MESSAGE_KEY)){
			return null;
		}
		OscopeDataMessage msg = new OscopeDataMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * a message to convey a single channel of oscope data
	 * this can also be used to configure a channel - data would be zero length in that case
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= OSCOPE_DATA_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the channel field
	 */
	public int getChannel(){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * Tests if the current message containts the channel field
	 */
	boolean isChannelPresent(){
		return OSCOPE_DATA_MESSAGE_CHANNEL_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the captureId field
	 */
	public long getCaptureId(){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_CAPTURE_ID_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the captureId field
	 */
	boolean isCaptureIdPresent(){
		return OSCOPE_DATA_MESSAGE_CAPTURE_ID_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the gain field
	 */
	public double getGain(){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_GAIN_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the gain field
	 */
	boolean isGainPresent(){
		return OSCOPE_DATA_MESSAGE_GAIN_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the offset field
	 */
	public double getOffset(){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_OFFSET_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the offset field
	 */
	boolean isOffsetPresent(){
		return OSCOPE_DATA_MESSAGE_OFFSET_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the source field
	 * sink-source that data is captured from
	 */
	public int getSource(){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_SOURCE_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * Tests if the current message containts the source field
	 * sink-source that data is captured from
	 */
	boolean isSourcePresent(){
		return OSCOPE_DATA_MESSAGE_SOURCE_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the data field
	 * @param i0 - index of data sequence.
	 */
	public int getData(int i0){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		return m_buf.readInt8(i );
	}
	/**
	 * A setter for the data field
	 * @param i0 - index of data sequence.
	 * @param data
	 */
	public void setData(int i0, int data){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeInt8(i , data);
	}
	/**
	 * A function to initialize a Oscope Data Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initData(int n){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Oscope Data Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getDataSequenceLength(){
		int i = 0;
		i = i + OSCOPE_DATA_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
