/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a SonarAScanMessage
 */
public class SonarAScanMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int SONAR_A_SCAN_MESSAGE_MAX_ORDINAL = 8;

	private static final int SONAR_A_SCAN_MESSAGE_LENGTH = 32;

	//These values are used to index into this message to access the various fields.
	private static final int SONAR_A_SCAN_MESSAGE_CAPTURE_ID_INDEX = 8;
	private static final int SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_INDEX = 24;
	private static final int SONAR_A_SCAN_MESSAGE_FIRST_SAMPLE_INDEX_INDEX = 12;
	private static final int SONAR_A_SCAN_MESSAGE_SAMPLE_RATE_INDEX = 20;
	private static final int SONAR_A_SCAN_MESSAGE_TOTAL_SAMPLE_NUM_INDEX = 16;
	private static final int SONAR_A_SCAN_MESSAGE_TYPE_INDEX = 28;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int SONAR_A_SCAN_MESSAGE_CAPTURE_ID_ORDINAL = 3;
	private static final int SONAR_A_SCAN_MESSAGE_FIRST_SAMPLE_INDEX_ORDINAL = 4;
	private static final int SONAR_A_SCAN_MESSAGE_SAMPLE_RATE_ORDINAL = 6;
	private static final int SONAR_A_SCAN_MESSAGE_TOTAL_SAMPLE_NUM_ORDINAL = 5;
	private static final int SONAR_A_SCAN_MESSAGE_TYPE_ORDINAL = 8;

	//Bit Nums

	//Sequence Element Byte Counts
	private static final int SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 4;
	/**
	 * A constructor to create a SonarAScanMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey a single A-scan of sonar data
	 * This doesn't contain any info about the data, like what transmit pulse was used or whatever
	 * Let's assume for now that info will be transferred some other way
	 * This message assumes that the  total a-scan will be sent over multiple messages
	 * This message can be used as a request if captureId and firstSample index are specified and zero
	 * In this case, sampleRate and data can be NAN, empty respectively, but they don't really matter
	 * It is assumed that a device will not respond right away if it doesn't have data yet, 
	 * instead it will simply drop the message and wait for a subsequent one.
	 * @param buf - the message buffer to add the message to
	 */
	private SonarAScanMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a SonarAScanMessage for transmission.
	 * A message to convey a single A-scan of sonar data
	 * This doesn't contain any info about the data, like what transmit pulse was used or whatever
	 * Let's assume for now that info will be transferred some other way
	 * This message assumes that the  total a-scan will be sent over multiple messages
	 * This message can be used as a request if captureId and firstSample index are specified and zero
	 * In this case, sampleRate and data can be NAN, empty respectively, but they don't really matter
	 * It is assumed that a device will not respond right away if it doesn't have data yet, 
	 * instead it will simply drop the message and wait for a subsequent one.
	 * @param buf - the message buffer to add the message to
	 * @param captureId - a unique identifier of the entire a-scan data set. This is set by the device.
	 * @param firstSampleIndex - the index of the first element of the sequence.
	 * @param totalSampleNum - the number of datapoints in this data set. This is defined by the device
	 * @param sampleRate - the sample rate reported from the data source
	 * @param type - An enum for conveying the type of data in an A-scan
	 */
	public static SonarAScanMessage make(BlueberryBuffer buf, long captureId, long firstSampleIndex, long totalSampleNum, double sampleRate, AScanTypeEnum type) {
		SonarAScanMessage msg = new SonarAScanMessage(buf);
		msg.setupHeader(SONAR_A_SCAN_MESSAGE_KEY, SONAR_A_SCAN_MESSAGE_MAX_ORDINAL, SONAR_A_SCAN_MESSAGE_LENGTH);
		msg.m_buf.writeUint32(SONAR_A_SCAN_MESSAGE_CAPTURE_ID_INDEX, captureId);
		msg.m_buf.writeUint32(SONAR_A_SCAN_MESSAGE_FIRST_SAMPLE_INDEX_INDEX, firstSampleIndex);
		msg.m_buf.writeUint32(SONAR_A_SCAN_MESSAGE_TOTAL_SAMPLE_NUM_INDEX, totalSampleNum);
		msg.m_buf.writeFloat32(SONAR_A_SCAN_MESSAGE_SAMPLE_RATE_INDEX, sampleRate);
		msg.m_buf.writeUint8(SONAR_A_SCAN_MESSAGE_TYPE_INDEX, type.getValue());
		msg.m_buf.writeUint16(SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty SonarAScanMessage for transmission.
	 * A message to convey a single A-scan of sonar data
	 * This doesn't contain any info about the data, like what transmit pulse was used or whatever
	 * Let's assume for now that info will be transferred some other way
	 * This message assumes that the  total a-scan will be sent over multiple messages
	 * This message can be used as a request if captureId and firstSample index are specified and zero
	 * In this case, sampleRate and data can be NAN, empty respectively, but they don't really matter
	 * It is assumed that a device will not respond right away if it doesn't have data yet, 
	 * instead it will simply drop the message and wait for a subsequent one.
	 * @param buf - the message buffer to add the message to
	 */
	public static SonarAScanMessage makeEmpty(BlueberryBuffer buf) {
		SonarAScanMessage msg = new SonarAScanMessage(buf);
		msg.setupHeader(SONAR_A_SCAN_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a SonarAScanMessage.
	 * A message to convey a single A-scan of sonar data
	 * This doesn't contain any info about the data, like what transmit pulse was used or whatever
	 * Let's assume for now that info will be transferred some other way
	 * This message assumes that the  total a-scan will be sent over multiple messages
	 * This message can be used as a request if captureId and firstSample index are specified and zero
	 * In this case, sampleRate and data can be NAN, empty respectively, but they don't really matter
	 * It is assumed that a device will not respond right away if it doesn't have data yet, 
	 * instead it will simply drop the message and wait for a subsequent one.
	 * @param buf - the message buffer to add the message to
	 */
	public static SonarAScanMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, SONAR_A_SCAN_MESSAGE_KEY)){
			return null;
		}
		SonarAScanMessage msg = new SonarAScanMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey a single A-scan of sonar data
	 * This doesn't contain any info about the data, like what transmit pulse was used or whatever
	 * Let's assume for now that info will be transferred some other way
	 * This message assumes that the  total a-scan will be sent over multiple messages
	 * This message can be used as a request if captureId and firstSample index are specified and zero
	 * In this case, sampleRate and data can be NAN, empty respectively, but they don't really matter
	 * It is assumed that a device will not respond right away if it doesn't have data yet, 
	 * instead it will simply drop the message and wait for a subsequent one.
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= SONAR_A_SCAN_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the captureId field
	 * a unique identifier of the entire a-scan data set. This is set by the device.
	 */
	public long getCaptureId(){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_CAPTURE_ID_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the captureId field
	 * a unique identifier of the entire a-scan data set. This is set by the device.
	 */
	boolean isCaptureIdPresent(){
		return SONAR_A_SCAN_MESSAGE_CAPTURE_ID_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the firstSampleIndex field
	 * the index of the first element of the sequence.
	 */
	public long getFirstSampleIndex(){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_FIRST_SAMPLE_INDEX_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the firstSampleIndex field
	 * the index of the first element of the sequence.
	 */
	boolean isFirstSampleIndexPresent(){
		return SONAR_A_SCAN_MESSAGE_FIRST_SAMPLE_INDEX_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the totalSampleNum field
	 * the number of datapoints in this data set. This is defined by the device
	 */
	public long getTotalSampleNum(){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_TOTAL_SAMPLE_NUM_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the totalSampleNum field
	 * the number of datapoints in this data set. This is defined by the device
	 */
	boolean isTotalSampleNumPresent(){
		return SONAR_A_SCAN_MESSAGE_TOTAL_SAMPLE_NUM_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the sampleRate field
	 * the sample rate reported from the data source
	 */
	public double getSampleRate(){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_SAMPLE_RATE_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the sampleRate field
	 * the sample rate reported from the data source
	 */
	boolean isSampleRatePresent(){
		return SONAR_A_SCAN_MESSAGE_SAMPLE_RATE_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the data field
	 * @param i0 - index of data sequence.
	 */
	public double getData(int i0){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the data field
	 * @param i0 - index of data sequence.
	 * @param data
	 */
	public void setData(int i0, double data){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , data);
	}
	/**
	 * A getter for the type field
	 * An enum for conveying the type of data in an A-scan
	 */
	public AScanTypeEnum getType(){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_TYPE_INDEX;
		return AScanTypeEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the type field
	 * An enum for conveying the type of data in an A-scan
	 */
	boolean isTypePresent(){
		return SONAR_A_SCAN_MESSAGE_TYPE_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A function to initialize a Float Sequence
	 * a handy sequence of 32-bit floats. This is like an array but variable length
	 * @param n - the number of elements of this sequence
	 */
	public void initData(int n){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Float Sequence
	 * a handy sequence of 32-bit floats. This is like an array but variable length
	 * @return - the number of elements in the sequence
	 */
	public int getDataSequenceLength(){
		int i = 0;
		i = i + SONAR_A_SCAN_MESSAGE_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
