/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a SpiTransactionMessage
 */
public class SpiTransactionMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int SPI_TRANSACTION_MESSAGE_MAX_ORDINAL = 10;

	private static final int SPI_TRANSACTION_MESSAGE_LENGTH = 24;

	//These values are used to index into this message to access the various fields.
	private static final int SPI_TRANSACTION_MESSAGE_BAUD_DIV_INDEX = 10;
	private static final int SPI_TRANSACTION_MESSAGE_CLOCK_SPEC_INDEX = 11;
	private static final int SPI_TRANSACTION_MESSAGE_CS_PIN_INDEX = 9;
	private static final int SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_INDEX = 14;
	private static final int SPI_TRANSACTION_MESSAGE_NUM_BYTES_INDEX = 12;
	private static final int SPI_TRANSACTION_MESSAGE_SPI_DEV_INDEX = 8;
	private static final int SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX = 20;
	private static final int SPI_TRANSACTION_MESSAGE_TRANSACTION_ID_INDEX = 16;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int SPI_TRANSACTION_MESSAGE_BAUD_DIV_ORDINAL = 5;
	private static final int SPI_TRANSACTION_MESSAGE_CLOCK_SPEC_ORDINAL = 6;
	private static final int SPI_TRANSACTION_MESSAGE_CS_PIN_ORDINAL = 4;
	private static final int SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_ORDINAL = 8;
	private static final int SPI_TRANSACTION_MESSAGE_NUM_BYTES_ORDINAL = 7;
	private static final int SPI_TRANSACTION_MESSAGE_SPI_DEV_ORDINAL = 3;
	private static final int SPI_TRANSACTION_MESSAGE_TRANSACTION_ID_ORDINAL = 9;

	//Bit Nums
	private static final int SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_BIT_NUM = 0;

	//Sequence Element Byte Counts
	private static final int SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 4;
	/**
	 * A constructor to create a SpiTransactionMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 *  A message to define an SPI transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 */
	private SpiTransactionMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a SpiTransactionMessage for transmission.
	 *  A message to define an SPI transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 * @param spiDev
	 * @param csPin - an enum to specify a port pin
	 * this is constructed with the top nibble representing the port and the bottom nibble the pin number
	 * @param baudDiv
	 * @param clockSpec
	 * @param numBytes -  The number of bytes contained in this SPI transaction
	 * @param deAssertCs -  If we want to de-assert CS at the end of this SPI transaction
	 * @param transactionId -  Unique ID for the transaction
	 */
	public static SpiTransactionMessage make(BlueberryBuffer buf, SpiDevBbEnum spiDev, PortPinEnum csPin, BaudDivBbEnum baudDiv, ClockSpecBbEnum clockSpec, int numBytes, boolean deAssertCs, int transactionId) {
		SpiTransactionMessage msg = new SpiTransactionMessage(buf);
		msg.setupHeader(SPI_TRANSACTION_MESSAGE_KEY, SPI_TRANSACTION_MESSAGE_MAX_ORDINAL, SPI_TRANSACTION_MESSAGE_LENGTH);
		msg.m_buf.writeUint8(SPI_TRANSACTION_MESSAGE_SPI_DEV_INDEX, spiDev.getValue());
		msg.m_buf.writeUint8(SPI_TRANSACTION_MESSAGE_CS_PIN_INDEX, csPin.getValue());
		msg.m_buf.writeUint8(SPI_TRANSACTION_MESSAGE_BAUD_DIV_INDEX, baudDiv.getValue());
		msg.m_buf.writeUint8(SPI_TRANSACTION_MESSAGE_CLOCK_SPEC_INDEX, clockSpec.getValue());
		msg.m_buf.writeUint16(SPI_TRANSACTION_MESSAGE_NUM_BYTES_INDEX, numBytes);
		msg.m_buf.writeBit(SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_INDEX, SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_BIT_NUM, deAssertCs);
		msg.m_buf.writeInt32(SPI_TRANSACTION_MESSAGE_TRANSACTION_ID_INDEX, transactionId);
		msg.m_buf.writeUint16(SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty SpiTransactionMessage for transmission.
	 *  A message to define an SPI transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 */
	public static SpiTransactionMessage makeEmpty(BlueberryBuffer buf) {
		SpiTransactionMessage msg = new SpiTransactionMessage(buf);
		msg.setupHeader(SPI_TRANSACTION_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a SpiTransactionMessage.
	 *  A message to define an SPI transaction to be sent out
	 * @param buf - the message buffer to add the message to
	 */
	public static SpiTransactionMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, SPI_TRANSACTION_MESSAGE_KEY)){
			return null;
		}
		SpiTransactionMessage msg = new SpiTransactionMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 *  A message to define an SPI transaction to be sent out
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= SPI_TRANSACTION_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the spiDev field
	 */
	public SpiDevBbEnum getSpiDev(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_SPI_DEV_INDEX;
		return SpiDevBbEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the spiDev field
	 */
	boolean isSpiDevPresent(){
		return SPI_TRANSACTION_MESSAGE_SPI_DEV_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the csPin field
	 * an enum to specify a port pin
	 * this is constructed with the top nibble representing the port and the bottom nibble the pin number
	 */
	public PortPinEnum getCsPin(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_CS_PIN_INDEX;
		return PortPinEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the csPin field
	 * an enum to specify a port pin
	 * this is constructed with the top nibble representing the port and the bottom nibble the pin number
	 */
	boolean isCsPinPresent(){
		return SPI_TRANSACTION_MESSAGE_CS_PIN_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the baudDiv field
	 */
	public BaudDivBbEnum getBaudDiv(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_BAUD_DIV_INDEX;
		return BaudDivBbEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the baudDiv field
	 */
	boolean isBaudDivPresent(){
		return SPI_TRANSACTION_MESSAGE_BAUD_DIV_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the clockSpec field
	 */
	public ClockSpecBbEnum getClockSpec(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_CLOCK_SPEC_INDEX;
		return ClockSpecBbEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the clockSpec field
	 */
	boolean isClockSpecPresent(){
		return SPI_TRANSACTION_MESSAGE_CLOCK_SPEC_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the numBytes field
	 *  The number of bytes contained in this SPI transaction
	 */
	public int getNumBytes(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_NUM_BYTES_INDEX;
		return m_buf.readUint16(i );
	}
	/**
	 * Tests if the current message containts the numBytes field
	 *  The number of bytes contained in this SPI transaction
	 */
	boolean isNumBytesPresent(){
		return SPI_TRANSACTION_MESSAGE_NUM_BYTES_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the deAssertCs field
	 *  If we want to de-assert CS at the end of this SPI transaction
	 */
	public boolean isDeAssertCs(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_INDEX;
		return m_buf.readBit(i , SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_BIT_NUM);
	}
	/**
	 * Tests if the current message containts the deAssertCs field
	 *  If we want to de-assert CS at the end of this SPI transaction
	 */
	boolean isDeAssertCsPresent(){
		return SPI_TRANSACTION_MESSAGE_DE_ASSERT_CS_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the transactionId field
	 *  Unique ID for the transaction
	 */
	public int getTransactionId(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_TRANSACTION_ID_INDEX;
		return m_buf.readInt32(i );
	}
	/**
	 * Tests if the current message containts the transactionId field
	 *  Unique ID for the transaction
	 */
	boolean isTransactionIdPresent(){
		return SPI_TRANSACTION_MESSAGE_TRANSACTION_ID_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the transactionData field
	 * @param i0 - index of transactionData sequence.
	 */
	public long getTransactionData(int i0){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		return m_buf.readUint32(i );
	}
	/**
	 * A setter for the transactionData field
	 * @param i0 - index of transactionData sequence.
	 * @param transactionData
	 */
	public void setTransactionData(int i0, long transactionData){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint32(i , transactionData);
	}
	/**
	 * A function to initialize a Spi Transaction Data
	 * @param n - the number of elements of this sequence
	 */
	public void initTransactionData(int n){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Spi Transaction Data
	 * @return - the number of elements in the sequence
	 */
	public int getTransactionDataSequenceLength(){
		int i = 0;
		i = i + SPI_TRANSACTION_MESSAGE_TRANSACTION_DATA_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
