/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a ThermistorConfigMessage
 */
public class ThermistorConfigMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int THERMISTOR_CONFIG_MESSAGE_MAX_ORDINAL = 3;

	private static final int THERMISTOR_CONFIG_MESSAGE_LENGTH = 12;

	//These values are used to index into this message to access the various fields.
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_ADC_CHANNEL_INDEX = 2;
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_CHANNEL_INDEX = 0;
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_C_0_INDEX = 4;
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_C_1_INDEX = 8;
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_C_2_INDEX = 12;
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_C_3_INDEX = 16;
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_ENABLED_INDEX = 1;
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema

	//Bit Nums
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_ENABLED_BIT_NUM = 0;

	//Sequence Element Byte Counts
	private static final int THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT = 20;
	/**
	 * A constructor to create a ThermistorConfigMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey config parameters for Thermistors
	 * @param buf - the message buffer to add the message to
	 */
	private ThermistorConfigMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a ThermistorConfigMessage for transmission.
	 * A message to convey config parameters for Thermistors
	 * @param buf - the message buffer to add the message to
	 */
	public static ThermistorConfigMessage make(BlueberryBuffer buf) {
		ThermistorConfigMessage msg = new ThermistorConfigMessage(buf);
		msg.setupHeader(THERMISTOR_CONFIG_MESSAGE_KEY, THERMISTOR_CONFIG_MESSAGE_MAX_ORDINAL, THERMISTOR_CONFIG_MESSAGE_LENGTH);
		msg.m_buf.writeUint16(THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX, INVALID_BLOCK);//clear sequence header
		return msg;
	}
	/**
	 * A constructor to create an empty ThermistorConfigMessage for transmission.
	 * A message to convey config parameters for Thermistors
	 * @param buf - the message buffer to add the message to
	 */
	public static ThermistorConfigMessage makeEmpty(BlueberryBuffer buf) {
		ThermistorConfigMessage msg = new ThermistorConfigMessage(buf);
		msg.setupHeader(THERMISTOR_CONFIG_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a ThermistorConfigMessage.
	 * A message to convey config parameters for Thermistors
	 * @param buf - the message buffer to add the message to
	 */
	public static ThermistorConfigMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, THERMISTOR_CONFIG_MESSAGE_KEY)){
			return null;
		}
		ThermistorConfigMessage msg = new ThermistorConfigMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey config parameters for Thermistors
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= THERMISTOR_CONFIG_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the channel field
	 * the thermistor channel
	 * @param i0 - index of config sequence.
	 */
	public int getConfigChannel(int i0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the channel field
	 * the thermistor channel
	 * @param i0 - index of config sequence.
	 * @param channel - the thermistor channel
	 */
	public void setConfigChannel(int i0, int channel){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , channel);
	}
	/**
	 * A getter for the enabled field
	 * indicates that the channel is enabled
	 * @param i0 - index of config sequence.
	 */
	public boolean isConfigEnabled(int i0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_ENABLED_INDEX;
		return m_buf.readBit(i , THERMISTOR_CONFIG_MESSAGE_CONFIG_ENABLED_BIT_NUM);
	}
	/**
	 * A setter for the enabled field
	 * indicates that the channel is enabled
	 * @param i0 - index of config sequence.
	 * @param enabled - indicates that the channel is enabled
	 */
	public void setConfigEnabled(int i0, boolean enabled){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_ENABLED_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeBit(i , THERMISTOR_CONFIG_MESSAGE_CONFIG_ENABLED_BIT_NUM, enabled);
	}
	/**
	 * A getter for the adcChannel field
	 * the adc channel that is used as a source for the thermistor calculation
	 * @param i0 - index of config sequence.
	 */
	public int getConfigAdcChannel(int i0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_ADC_CHANNEL_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * A setter for the adcChannel field
	 * the adc channel that is used as a source for the thermistor calculation
	 * @param i0 - index of config sequence.
	 * @param adcChannel - the adc channel that is used as a source for the thermistor calculation
	 */
	public void setConfigAdcChannel(int i0, int adcChannel){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_ADC_CHANNEL_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeUint8(i , adcChannel);
	}
	/**
	 * A getter for the c0 field
	 * the 1st term parameter. If setting up with beta then c0 = 1/T0 - typically (1.0f/298.15f)     
	 * @param i0 - index of config sequence.
	 */
	public double getConfigC0(int i0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_0_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the c0 field
	 * the 1st term parameter. If setting up with beta then c0 = 1/T0 - typically (1.0f/298.15f)     
	 * @param i0 - index of config sequence.
	 * @param c0 - the 1st term parameter. If setting up with beta then c0 = 1/T0 - typically (1.0f/298.15f)     
	 */
	public void setConfigC0(int i0, double c0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_0_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , c0);
	}
	/**
	 * A getter for the c1 field
	 * the 2nd term parameter. If setting up with beta then c1 = 1/beta - typically (1.0f/3380.0f)   
	 * @param i0 - index of config sequence.
	 */
	public double getConfigC1(int i0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_1_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the c1 field
	 * the 2nd term parameter. If setting up with beta then c1 = 1/beta - typically (1.0f/3380.0f)   
	 * @param i0 - index of config sequence.
	 * @param c1 - the 2nd term parameter. If setting up with beta then c1 = 1/beta - typically (1.0f/3380.0f)   
	 */
	public void setConfigC1(int i0, double c1){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_1_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , c1);
	}
	/**
	 * A getter for the c2 field
	 * the 3rd term parameter. If setting up with beta then c2 = 0.0f                                
	 * @param i0 - index of config sequence.
	 */
	public double getConfigC2(int i0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_2_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the c2 field
	 * the 3rd term parameter. If setting up with beta then c2 = 0.0f                                
	 * @param i0 - index of config sequence.
	 * @param c2 - the 3rd term parameter. If setting up with beta then c2 = 0.0f                                
	 */
	public void setConfigC2(int i0, double c2){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_2_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , c2);
	}
	/**
	 * A getter for the c3 field
	 * the 4th term parameter. If setting up with beta then c3 = 0.0f                                
	 * @param i0 - index of config sequence.
	 */
	public double getConfigC3(int i0){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_3_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * A setter for the c3 field
	 * the 4th term parameter. If setting up with beta then c3 = 0.0f                                
	 * @param i0 - index of config sequence.
	 * @param c3 - the 4th term parameter. If setting up with beta then c3 = 0.0f                                
	 */
	public void setConfigC3(int i0, double c3){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		i = getSequenceElementBlock(i, i0);
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_C_3_INDEX;
		if(i < 0){
			return;//bail because a sequence was not initialized
		}
		m_buf.writeFloat32(i , c3);
	}
	/**
	 * A function to initialize a Thermistor Config Sequence
	 * @param n - the number of elements of this sequence
	 */
	public void initConfig(int n){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		int bs = THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_SEQUENCE_ELEMENT_BYTE_COUNT;
		initSequenceBlock(i,  bs, n);
	}
	/**
	 * Gets the defined length of a sequence Thermistor Config Sequence
	 * @return - the number of elements in the sequence
	 */
	public int getConfigSequenceLength(){
		int i = 0;
		i = i + THERMISTOR_CONFIG_MESSAGE_CONFIG_PLACEHOLDER_INDEX;
		//i is now the index of this sequence field header
		return getSequenceLength(i);
	}
}
