/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a TimeSyncMessage
 */
public class TimeSyncMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int TIME_SYNC_MESSAGE_MAX_ORDINAL = 4;

	private static final int TIME_SYNC_MESSAGE_LENGTH = 24;

	//These values are used to index into this message to access the various fields.
	private static final int TIME_SYNC_MESSAGE_LAST_RECEIVED_TIME_INDEX = 16;
	private static final int TIME_SYNC_MESSAGE_SENDER_TIME_INDEX = 8;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int TIME_SYNC_MESSAGE_LAST_RECEIVED_TIME_ORDINAL = 4;
	private static final int TIME_SYNC_MESSAGE_SENDER_TIME_ORDINAL = 3;

	//Bit Nums
	/**
	 * A constructor to create a TimeSyncMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * An improved message for time synchronization that uses the new Time64 deined type
	 * @param buf - the message buffer to add the message to
	 */
	private TimeSyncMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a TimeSyncMessage for transmission.
	 * An improved message for time synchronization that uses the new Time64 deined type
	 * @param buf - the message buffer to add the message to
	 * @param senderTime - a measure of time in 100ns increments since an epoch of January 1st 2000
	 * @param lastReceivedTime - a measure of time in 100ns increments since an epoch of January 1st 2000
	 */
	public static TimeSyncMessage make(BlueberryBuffer buf, long senderTime, long lastReceivedTime) {
		TimeSyncMessage msg = new TimeSyncMessage(buf);
		msg.setupHeader(TIME_SYNC_MESSAGE_KEY, TIME_SYNC_MESSAGE_MAX_ORDINAL, TIME_SYNC_MESSAGE_LENGTH);
		msg.m_buf.writeUint64(TIME_SYNC_MESSAGE_SENDER_TIME_INDEX, senderTime);
		msg.m_buf.writeUint64(TIME_SYNC_MESSAGE_LAST_RECEIVED_TIME_INDEX, lastReceivedTime);
		return msg;
	}
	/**
	 * A constructor to create an empty TimeSyncMessage for transmission.
	 * An improved message for time synchronization that uses the new Time64 deined type
	 * @param buf - the message buffer to add the message to
	 */
	public static TimeSyncMessage makeEmpty(BlueberryBuffer buf) {
		TimeSyncMessage msg = new TimeSyncMessage(buf);
		msg.setupHeader(TIME_SYNC_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a TimeSyncMessage.
	 * An improved message for time synchronization that uses the new Time64 deined type
	 * @param buf - the message buffer to add the message to
	 */
	public static TimeSyncMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, TIME_SYNC_MESSAGE_KEY)){
			return null;
		}
		TimeSyncMessage msg = new TimeSyncMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * An improved message for time synchronization that uses the new Time64 deined type
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= TIME_SYNC_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the senderTime field
	 * a measure of time in 100ns increments since an epoch of January 1st 2000
	 */
	public long getSenderTime(){
		int i = 0;
		i = i + TIME_SYNC_MESSAGE_SENDER_TIME_INDEX;
		return m_buf.readUint64(i );
	}
	/**
	 * Tests if the current message containts the senderTime field
	 * a measure of time in 100ns increments since an epoch of January 1st 2000
	 */
	boolean isSenderTimePresent(){
		return TIME_SYNC_MESSAGE_SENDER_TIME_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the lastReceivedTime field
	 * a measure of time in 100ns increments since an epoch of January 1st 2000
	 */
	public long getLastReceivedTime(){
		int i = 0;
		i = i + TIME_SYNC_MESSAGE_LAST_RECEIVED_TIME_INDEX;
		return m_buf.readUint64(i );
	}
	/**
	 * Tests if the current message containts the lastReceivedTime field
	 * a measure of time in 100ns increments since an epoch of January 1st 2000
	 */
	boolean isLastReceivedTimePresent(){
		return TIME_SYNC_MESSAGE_LAST_RECEIVED_TIME_ORDINAL <= (getMaxOrdinal());
	}
}
