/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a TimeMessage
 */
public class TimeMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int TIME_MESSAGE_MAX_ORDINAL = 4;

	private static final int TIME_MESSAGE_LENGTH = 16;

	//These values are used to index into this message to access the various fields.
	private static final int TIME_MESSAGE_HOST_TIME_INDEX = 8;
	private static final int TIME_MESSAGE_LOCAL_TIME_INDEX = 12;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int TIME_MESSAGE_HOST_TIME_ORDINAL = 3;
	private static final int TIME_MESSAGE_LOCAL_TIME_ORDINAL = 4;

	//Bit Nums
	/**
	 * A constructor to create a TimeMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 */
	private TimeMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a TimeMessage for transmission.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 * @param hostTime - time in milliseconds from program start according to the bus controller
	 * @param localTime - time in milliseconds from program start according to sender of this packet
	 */
	public static TimeMessage make(BlueberryBuffer buf, long hostTime, long localTime) {
		TimeMessage msg = new TimeMessage(buf);
		msg.setupHeader(TIME_MESSAGE_KEY, TIME_MESSAGE_MAX_ORDINAL, TIME_MESSAGE_LENGTH);
		msg.m_buf.writeUint32(TIME_MESSAGE_HOST_TIME_INDEX, hostTime);
		msg.m_buf.writeUint32(TIME_MESSAGE_LOCAL_TIME_INDEX, localTime);
		return msg;
	}
	/**
	 * A constructor to create an empty TimeMessage for transmission.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 */
	public static TimeMessage makeEmpty(BlueberryBuffer buf) {
		TimeMessage msg = new TimeMessage(buf);
		msg.setupHeader(TIME_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a TimeMessage.
	 * A message to convey the unique ID of this devices
	 * @param buf - the message buffer to add the message to
	 */
	public static TimeMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, TIME_MESSAGE_KEY)){
			return null;
		}
		TimeMessage msg = new TimeMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey the unique ID of this devices
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= TIME_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the hostTime field
	 * time in milliseconds from program start according to the bus controller
	 */
	public long getHostTime(){
		int i = 0;
		i = i + TIME_MESSAGE_HOST_TIME_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the hostTime field
	 * time in milliseconds from program start according to the bus controller
	 */
	boolean isHostTimePresent(){
		return TIME_MESSAGE_HOST_TIME_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the localTime field
	 * time in milliseconds from program start according to sender of this packet
	 */
	public long getLocalTime(){
		int i = 0;
		i = i + TIME_MESSAGE_LOCAL_TIME_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the localTime field
	 * time in milliseconds from program start according to sender of this packet
	 */
	boolean isLocalTimePresent(){
		return TIME_MESSAGE_LOCAL_TIME_ORDINAL <= (getMaxOrdinal());
	}
}
