/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a VersionMessage
 */
public class VersionMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int VERSION_MESSAGE_MAX_ORDINAL = 6;

	private static final int VERSION_MESSAGE_LENGTH = 16;

	//These values are used to index into this message to access the various fields.
	private static final int VERSION_MESSAGE_FIRMWARE_VERSION_INDEX = 8;
	private static final int VERSION_MESSAGE_HARDWARE_REV_INDEX = 12;
	private static final int VERSION_MESSAGE_HARDWARE_TYPE_INDEX = 14;
	private static final int VERSION_MESSAGE_MCU_TYPE_INDEX = 13;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int VERSION_MESSAGE_FIRMWARE_VERSION_ORDINAL = 3;
	private static final int VERSION_MESSAGE_HARDWARE_REV_ORDINAL = 4;
	private static final int VERSION_MESSAGE_HARDWARE_TYPE_ORDINAL = 5;
	private static final int VERSION_MESSAGE_MCU_TYPE_ORDINAL = 6;

	//Bit Nums
	/**
	 * A constructor to create a VersionMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * A message to convey hardware and firmware versions in addition to hardware type
	 * @param buf - the message buffer to add the message to
	 */
	private VersionMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a VersionMessage for transmission.
	 * A message to convey hardware and firmware versions in addition to hardware type
	 * @param buf - the message buffer to add the message to
	 * @param firmwareVersion
	 * @param hardwareRev
	 * @param hardwareType - an enum to convey PCB type
	 * @param mcuType
	 */
	public static VersionMessage make(BlueberryBuffer buf, long firmwareVersion, int hardwareRev, HwTypeEnum hardwareType, McuTypeEnum mcuType) {
		VersionMessage msg = new VersionMessage(buf);
		msg.setupHeader(VERSION_MESSAGE_KEY, VERSION_MESSAGE_MAX_ORDINAL, VERSION_MESSAGE_LENGTH);
		msg.m_buf.writeUint32(VERSION_MESSAGE_FIRMWARE_VERSION_INDEX, firmwareVersion);
		msg.m_buf.writeUint8(VERSION_MESSAGE_HARDWARE_REV_INDEX, hardwareRev);
		msg.m_buf.writeUint16(VERSION_MESSAGE_HARDWARE_TYPE_INDEX, hardwareType.getValue());
		msg.m_buf.writeUint8(VERSION_MESSAGE_MCU_TYPE_INDEX, mcuType.getValue());
		return msg;
	}
	/**
	 * A constructor to create an empty VersionMessage for transmission.
	 * A message to convey hardware and firmware versions in addition to hardware type
	 * @param buf - the message buffer to add the message to
	 */
	public static VersionMessage makeEmpty(BlueberryBuffer buf) {
		VersionMessage msg = new VersionMessage(buf);
		msg.setupHeader(VERSION_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a VersionMessage.
	 * A message to convey hardware and firmware versions in addition to hardware type
	 * @param buf - the message buffer to add the message to
	 */
	public static VersionMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, VERSION_MESSAGE_KEY)){
			return null;
		}
		VersionMessage msg = new VersionMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * A message to convey hardware and firmware versions in addition to hardware type
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= VERSION_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the firmwareVersion field
	 */
	public long getFirmwareVersion(){
		int i = 0;
		i = i + VERSION_MESSAGE_FIRMWARE_VERSION_INDEX;
		return m_buf.readUint32(i );
	}
	/**
	 * Tests if the current message containts the firmwareVersion field
	 */
	boolean isFirmwareVersionPresent(){
		return VERSION_MESSAGE_FIRMWARE_VERSION_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the hardwareRev field
	 */
	public int getHardwareRev(){
		int i = 0;
		i = i + VERSION_MESSAGE_HARDWARE_REV_INDEX;
		return m_buf.readUint8(i );
	}
	/**
	 * Tests if the current message containts the hardwareRev field
	 */
	boolean isHardwareRevPresent(){
		return VERSION_MESSAGE_HARDWARE_REV_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the hardwareType field
	 * an enum to convey PCB type
	 */
	public HwTypeEnum getHardwareType(){
		int i = 0;
		i = i + VERSION_MESSAGE_HARDWARE_TYPE_INDEX;
		return HwTypeEnum.lookup(m_buf.readUint16(i ));
	}
	/**
	 * Tests if the current message containts the hardwareType field
	 * an enum to convey PCB type
	 */
	boolean isHardwareTypePresent(){
		return VERSION_MESSAGE_HARDWARE_TYPE_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the mcuType field
	 */
	public McuTypeEnum getMcuType(){
		int i = 0;
		i = i + VERSION_MESSAGE_MCU_TYPE_INDEX;
		return McuTypeEnum.lookup(m_buf.readUint8(i ));
	}
	/**
	 * Tests if the current message containts the mcuType field
	 */
	boolean isMcuTypePresent(){
		return VERSION_MESSAGE_MCU_TYPE_ORDINAL <= (getMaxOrdinal());
	}
}
