/*
 * Copyright (c) 2025 Blue Robotics North Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

//*************************************************************************************
//*************************************************************************************
//ATTENTION! THIS FILE WAS AUTOGENERATED BY THE BLUEBERRY SCHEMA PARSER.
//It's probably not a good idea to modify it. :-P
//*************************************************************************************
//*************************************************************************************

package com.bluerobotics.blueberry.bb.blueberry.devices;

import com.bluerobotics.blueberry.transcoder.java.BlueberryMessage;
import com.bluerobotics.blueberry.transcoder.java.BlueberryBuffer;

/*
 * A class to read and write a WhosThereMessage
 */
public class WhosThereMessage extends BlueberryMessage implements BlueberryDevicesConstants {
	private static final int WHOS_THERE_MESSAGE_MAX_ORDINAL = 4;

	private static final int WHOS_THERE_MESSAGE_LENGTH = 16;

	//These values are used to index into this message to access the various fields.
	private static final int WHOS_THERE_MESSAGE_PROBABILITY_INDEX = 8;
	private static final int WHOS_THERE_MESSAGE_TIME_INDEX = 12;

	//The following values represent the ordinals of the fields of this message.
	//This corresponds to the order that they were defined in the schema
	private static final int WHOS_THERE_MESSAGE_PROBABILITY_ORDINAL = 3;
	private static final int WHOS_THERE_MESSAGE_TIME_ORDINAL = 4;

	//Bit Nums
	/**
	 * A constructor to create a WhosThereMessage.
	 * This does the bare minimum: it just wraps a buffer in a message.
	 * This is private so it should never be called outside of this class.
	 * The intent is that the static factory methods would be used instead.
	 * a request by the bus controller to all devices that have not communicated successfully recently
	 * the controller can specify the probability and timeframe that the peripherals will respond
	 * the peripherals will respond with an idPayload
	 * @param buf - the message buffer to add the message to
	 */
	private WhosThereMessage(BlueberryBuffer buf) {
		super(buf);
	}
	/**
	 * A constructor to create a WhosThereMessage for transmission.
	 * a request by the bus controller to all devices that have not communicated successfully recently
	 * the controller can specify the probability and timeframe that the peripherals will respond
	 * the peripherals will respond with an idPayload
	 * @param buf - the message buffer to add the message to
	 * @param probability - the probability that the peripheral will respond. 1.0 is 100% probability, 0.0 is zero.
	 * @param time - the time in seconds within which the device should respond.
	 */
	public static WhosThereMessage make(BlueberryBuffer buf, double probability, double time) {
		WhosThereMessage msg = new WhosThereMessage(buf);
		msg.setupHeader(WHOS_THERE_MESSAGE_KEY, WHOS_THERE_MESSAGE_MAX_ORDINAL, WHOS_THERE_MESSAGE_LENGTH);
		msg.m_buf.writeFloat32(WHOS_THERE_MESSAGE_PROBABILITY_INDEX, probability);
		msg.m_buf.writeFloat32(WHOS_THERE_MESSAGE_TIME_INDEX, time);
		return msg;
	}
	/**
	 * A constructor to create an empty WhosThereMessage for transmission.
	 * a request by the bus controller to all devices that have not communicated successfully recently
	 * the controller can specify the probability and timeframe that the peripherals will respond
	 * the peripherals will respond with an idPayload
	 * @param buf - the message buffer to add the message to
	 */
	public static WhosThereMessage makeEmpty(BlueberryBuffer buf) {
		WhosThereMessage msg = new WhosThereMessage(buf);
		msg.setupHeader(WHOS_THERE_MESSAGE_KEY, MIN_MAX_ORDINAL, MIN_MESSAGE_LENGTH);
		return msg;
	}
	/**
	 * A method to wrap a buffer of received data in a WhosThereMessage.
	 * a request by the bus controller to all devices that have not communicated successfully recently
	 * the controller can specify the probability and timeframe that the peripherals will respond
	 * the peripherals will respond with an idPayload
	 * @param buf - the message buffer to add the message to
	 */
	public static WhosThereMessage wrap(BlueberryBuffer buf) {
		if(!isModuleMessageKeyCorrect(buf, WHOS_THERE_MESSAGE_KEY)){
			return null;
		}
		WhosThereMessage msg = new WhosThereMessage(buf);
		return msg;
	}
	/**
	 * Tests if the current message ha all defined fields present.
	 * a request by the bus controller to all devices that have not communicated successfully recently
	 * the controller can specify the probability and timeframe that the peripherals will respond
	 * the peripherals will respond with an idPayload
	 */
	public boolean isFull(){
		return getMaxOrdinal() >= WHOS_THERE_MESSAGE_MAX_ORDINAL;
	}
	/**
	 * A getter for the probability field
	 * the probability that the peripheral will respond. 1.0 is 100% probability, 0.0 is zero.
	 */
	public double getProbability(){
		int i = 0;
		i = i + WHOS_THERE_MESSAGE_PROBABILITY_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the probability field
	 * the probability that the peripheral will respond. 1.0 is 100% probability, 0.0 is zero.
	 */
	boolean isProbabilityPresent(){
		return WHOS_THERE_MESSAGE_PROBABILITY_ORDINAL <= (getMaxOrdinal());
	}
	/**
	 * A getter for the time field
	 * the time in seconds within which the device should respond.
	 */
	public double getTime(){
		int i = 0;
		i = i + WHOS_THERE_MESSAGE_TIME_INDEX;
		return m_buf.readFloat32(i );
	}
	/**
	 * Tests if the current message containts the time field
	 * the time in seconds within which the device should respond.
	 */
	boolean isTimePresent(){
		return WHOS_THERE_MESSAGE_TIME_ORDINAL <= (getMaxOrdinal());
	}
}
